let REMOTE=(typeof fetch==='function'&&typeof location==='object'&&/^https?:$/.test(location.protocol||''))?null:false,TOK='',V=null,LAST='',BASE={},Q=Promise.resolve(),BOOT=null;
const K='artcorner_v2',CATS=['จิตรกรรม','ภาพพิมพ์','ดิจิทัลอาร์ต','ภาพถ่าย','ภาพวาดเส้น'],ST=['รอชำระ','ชำระแล้ว','จัดส่ง','สำเร็จ'],SHIP=60,RENT=100,RDAYS=30;
const g=(a,b,c)=>[a,b,c];
const H=x=>{let h=5381;for(const c of 'ac$'+x)h=(h*33)^c.charCodeAt(0);return (h>>>0).toString(36)};
const sv=b=>`<svg viewBox="0 0 400 500" preserveAspectRatio="xMidYMid slice" style="width:100%;height:100%;display:block">${b}</svg>`;
const SCN={
w1:sv(`<defs><linearGradient id="s1" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#3b1c6b"/><stop offset=".55" stop-color="#e04f9b"/><stop offset="1" stop-color="#ff9a3c"/></linearGradient></defs><rect width="400" height="500" fill="url(#s1)"/><circle cx="200" cy="270" r="60" fill="#ffd27a"/><path d="M0 300 Q100 280 200 300 T400 300 V500 H0Z" fill="#2a4d2f"/><path d="M0 360 Q100 340 200 360 T400 360 V500 H0Z" fill="#3f7a3a"/><path d="M0 430 Q100 410 200 430 T400 430 V500 H0Z" fill="#6aa84f"/><path d="M60 300v-40M70 300v-30M330 300v-45" stroke="#1a2a1a" stroke-width="4"/>`),
w2:sv(`<rect width="400" height="500" fill="#f4e3b1"/><path d="M0 0L150 120V420L0 500Z" fill="#3a2a20"/><path d="M400 0L250 120V420L400 500Z" fill="#c0562b"/><rect x="150" y="120" width="100" height="300" fill="#e8c77f"/><path d="M150 420L0 500H400L250 420Z" fill="#7a5a3a"/><g fill="#f4e3b1"><rect x="40" y="200" width="30" height="45"/><rect x="40" y="300" width="30" height="45"/><rect x="330" y="200" width="30" height="45"/><rect x="330" y="300" width="30" height="45"/></g><rect x="185" y="330" width="30" height="90" fill="#3a2a20"/>`),
w3:sv(`<rect width="400" height="500" fill="#1f3b73"/><g fill="none" stroke="#7be0d4" stroke-opacity=".35" stroke-width="3"><circle cx="120" cy="140" r="40"/><circle cx="120" cy="140" r="70"/><circle cx="300" cy="380" r="50"/><circle cx="300" cy="380" r="85"/></g><g transform="rotate(-25 200 250)"><ellipse cx="200" cy="250" rx="90" ry="38" fill="#ff8a5c"/><path d="M110 250L60 215Q75 250 60 285Z" fill="#ffb37a"/><circle cx="265" cy="240" r="6" fill="#1f3b73"/></g><g transform="rotate(200 270 130)"><ellipse cx="270" cy="130" rx="55" ry="22" fill="#b58cff"/><path d="M215 130L185 110Q195 130 185 150Z" fill="#d8c2ff"/></g>`),
w4:sv(`<defs><linearGradient id="s4" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#a7e8b5"/><stop offset="1" stop-color="#0f3b3b"/></linearGradient></defs><rect width="400" height="500" fill="url(#s4)"/><g fill="#4a9c8c" opacity=".55"><path d="M40 400L90 180L140 400Z"/><path d="M250 400L310 150L370 400Z"/></g><g fill="#1d6a5c" opacity=".8"><path d="M-10 500L60 230L130 500Z"/><path d="M150 500L220 200L290 500Z"/><path d="M280 500L350 260L420 500Z"/></g><rect y="300" width="400" height="60" fill="#fff" opacity=".22"/><rect y="380" width="400" height="40" fill="#fff" opacity=".18"/>`),
w5:sv(`<rect width="400" height="500" fill="#f7f5ef"/><g fill="none" stroke="#333" stroke-width="3" stroke-linejoin="round"><path d="M40 200L360 200L340 150L60 150Z"/><path d="M60 200v200M340 200v200M60 400H340"/><path d="M60 200q20 28 40 0q20 28 40 0q20 28 40 0q20 28 40 0q20 28 40 0q20 28 40 0q20 28 40 0"/><circle cx="130" cy="330" r="22"/><circle cx="185" cy="340" r="18"/><circle cx="235" cy="332" r="22"/><path d="M90 400L110 460M310 400L290 460"/></g>`),
w6:sv(`<rect width="400" height="500" fill="#2b2f6b"/><circle cx="200" cy="190" r="110" fill="#ffe680"/><g fill="#8fa8ff"><circle cx="70" cy="80" r="3"/><circle cx="330" cy="70" r="4"/><circle cx="60" cy="300" r="3"/><circle cx="350" cy="260" r="3"/></g><g fill="#15173a"><ellipse cx="200" cy="360" rx="70" ry="60"/><circle cx="200" cy="290" r="42"/><path d="M165 265L172 225L192 255ZM235 265L228 225L208 255Z"/><path d="M265 380q60 10 70-50" fill="none" stroke="#15173a" stroke-width="14" stroke-linecap="round"/></g><rect y="420" width="400" height="80" fill="#15173a"/>`),
w7:sv(`<defs><linearGradient id="s7" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#9fd3ff"/><stop offset="1" stop-color="#f0f0f0"/></linearGradient></defs><rect width="400" height="250" fill="url(#s7)"/><path d="M0 250L90 130L160 200L250 90L330 190L400 150V250Z" fill="#324a63"/><rect y="250" width="400" height="250" fill="#5f86a8"/><g transform="translate(0 500) scale(1 -1)" opacity=".55"><path d="M0 250L90 130L160 200L250 90L330 190L400 150V250Z" fill="#324a63"/></g><path d="M40 300H140M220 340H340M80 400H200M260 450H370" stroke="#fff" stroke-opacity=".3" stroke-width="2"/>`),
w8:sv(`<rect width="400" height="500" fill="#6b2145"/><g fill="#ffc2e0"><ellipse cx="200" cy="250" rx="35" ry="95"/><ellipse cx="200" cy="250" rx="35" ry="95" transform="rotate(-35 200 340)"/><ellipse cx="200" cy="250" rx="35" ry="95" transform="rotate(35 200 340)"/></g><g fill="#ff6fa8"><ellipse cx="200" cy="270" rx="28" ry="80" transform="rotate(-65 200 340)"/><ellipse cx="200" cy="270" rx="28" ry="80" transform="rotate(65 200 340)"/></g><path d="M0 400Q200 350 400 400V500H0Z" fill="#2f6b4a"/><ellipse cx="90" cy="440" rx="70" ry="18" fill="#3f8f5f"/><ellipse cx="320" cy="455" rx="60" ry="15" fill="#3f8f5f"/><circle cx="200" cy="330" r="12" fill="#ffd27a"/>`),
w9:sv(`<rect width="400" height="500" fill="#f2e8d5"/><circle cx="140" cy="160" r="90" fill="#e63946"/><rect x="190" y="200" width="160" height="200" fill="#1d3557"/><path d="M40 470L170 290L300 470Z" fill="#f4a261"/><circle cx="290" cy="130" r="38" fill="#2a9d8f"/><path d="M40 60H360M40 80H360" stroke="#1d3557" stroke-width="4"/><rect x="60" y="360" width="60" height="60" fill="#f2e8d5" stroke="#1d3557" stroke-width="4"/>`),
w10:sv(`<defs><pattern id="s10" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="10" cy="10" r="5" fill="#ff4d8d"/></pattern></defs><rect width="400" height="500" fill="#ffe14d"/><rect width="400" height="500" fill="url(#s10)" opacity=".55"/><path d="M110 190H290L270 400Q200 430 130 400Z" fill="#fff" stroke="#111" stroke-width="8" stroke-linejoin="round"/><path d="M290 220Q350 220 340 290Q335 330 275 335" fill="none" stroke="#111" stroke-width="8"/><path d="M125 230H275L262 380Q200 400 138 380Z" fill="#6b3a1e"/><path d="M160 150q-15-25 5-45M200 150q-15-25 5-45M240 150q-15-25 5-45" fill="none" stroke="#111" stroke-width="7" stroke-linecap="round"/><ellipse cx="200" cy="440" rx="110" ry="14" fill="#111"/>`),
w11:sv(`<rect width="400" height="500" fill="#f6d9c4"/><circle cx="270" cy="170" r="70" fill="#e8654a"/><path d="M0 330L110 230L200 330Z" fill="#7a8fa6"/><path d="M120 340L260 210L400 340Z" fill="#4f6a86"/><path d="M0 500V350Q100 320 200 350T400 340V500Z" fill="#2e4157"/><path d="M0 500V420Q120 390 240 420T400 410V500Z" fill="#1c2a3a"/>`),
w12:sv(`<defs><linearGradient id="s12" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#14103a"/><stop offset="1" stop-color="#d1477a"/></linearGradient></defs><rect width="400" height="500" fill="url(#s12)"/><circle cx="310" cy="110" r="34" fill="#fff3c4"/><g fill="#0c0a24"><rect x="10" y="260" width="60" height="240"/><rect x="80" y="200" width="50" height="300"/><rect x="140" y="290" width="70" height="210"/><rect x="220" y="170" width="55" height="330"/><rect x="285" y="250" width="60" height="250"/><rect x="350" y="310" width="50" height="190"/></g><g fill="#ffd166"><rect x="90" y="220" width="8" height="10"/><rect x="108" y="250" width="8" height="10"/><rect x="232" y="200" width="8" height="10"/><rect x="250" y="240" width="8" height="10"/><rect x="232" y="290" width="8" height="10"/><rect x="298" y="280" width="8" height="10"/><rect x="155" y="320" width="8" height="10"/><rect x="25" y="290" width="8" height="10"/><rect x="45" y="340" width="8" height="10"/></g>`),
w13:sv(`<rect width="400" height="500" fill="#fbf7ee"/><g fill="none" stroke="#222" stroke-width="3" stroke-linejoin="round"><path d="M200 250C150 130 60 130 60 200C60 250 130 280 200 260C130 290 90 380 130 400C170 420 195 330 200 290"/><path d="M200 250C250 130 340 130 340 200C340 250 270 280 200 260C270 290 310 380 270 400C230 420 205 330 200 290"/><path d="M200 230V330"/><path d="M200 230Q180 170 150 150M200 230Q220 170 250 150"/><circle cx="110" cy="195" r="22"/><circle cx="290" cy="195" r="22"/><circle cx="135" cy="370" r="10"/><circle cx="265" cy="370" r="10"/></g>`),
w14:sv(`<defs><linearGradient id="s14" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#ffe9c9"/><stop offset="1" stop-color="#ffb199"/></linearGradient></defs><rect width="400" height="500" fill="url(#s14)"/><circle cx="90" cy="110" r="42" fill="#fff5d6"/><rect y="300" width="400" height="200" fill="#4c8fb0"/><path d="M0 330Q50 315 100 330T200 330T300 330T400 330V500H0Z" fill="#3a7699"/><path d="M0 400Q50 385 100 400T200 400T300 400T400 400V500H0Z" fill="#2b5f80"/><path d="M200 130V310L280 310Z" fill="#fff"/><path d="M190 150V310L130 310Z" fill="#f4f1e8"/><path d="M120 320H290L265 350H145Z" fill="#7a3b2e"/>`),
w15:sv(`<rect width="400" height="500" fill="#9fd3ff"/><rect y="330" width="400" height="170" fill="#5c8a3a"/><g stroke="#3f6b2a" stroke-width="6"><path d="M90 340V220M200 340V180M310 340V240"/></g><g fill="#ffc21a"><circle cx="90" cy="200" r="46"/><circle cx="200" cy="160" r="56"/><circle cx="310" cy="220" r="46"/></g><g fill="#6b3f1a"><circle cx="90" cy="200" r="20"/><circle cx="200" cy="160" r="25"/><circle cx="310" cy="220" r="20"/></g><path d="M0 330Q100 300 200 330T400 320V500H0Z" fill="#6f9c45" opacity=".8"/>`),
w16:sv(`<rect width="400" height="500" fill="#1b2a4a"/><g transform="translate(200 250)" fill="none" stroke="#e5b93c" stroke-width="3"><path id="pt" d="M0 -40C25 -80 25 -130 0 -170C-25 -130 -25 -80 0 -40Z"/><use href="#pt" transform="rotate(30)"/><use href="#pt" transform="rotate(60)"/><use href="#pt" transform="rotate(90)"/><use href="#pt" transform="rotate(120)"/><use href="#pt" transform="rotate(150)"/><use href="#pt" transform="rotate(180)"/><use href="#pt" transform="rotate(210)"/><use href="#pt" transform="rotate(240)"/><use href="#pt" transform="rotate(270)"/><use href="#pt" transform="rotate(300)"/><use href="#pt" transform="rotate(330)"/><circle r="30"/><circle r="12" fill="#e5b93c"/><circle r="185" stroke-dasharray="4 8"/></g><g fill="#e5b93c"><circle cx="30" cy="30" r="6"/><circle cx="370" cy="30" r="6"/><circle cx="30" cy="470" r="6"/><circle cx="370" cy="470" r="6"/></g>`),
w17:sv(`<defs><linearGradient id="s17" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#5b3df5"/><stop offset="1" stop-color="#e04f9b"/></linearGradient></defs><rect width="400" height="500" fill="url(#s17)"/><path d="M0 120Q100 60 200 130T400 110V190Q300 240 200 180T0 200Z" fill="#7be0d4" opacity=".75"/><path d="M0 250Q120 190 220 260T400 240V330Q290 380 190 320T0 340Z" fill="#ffd166" opacity=".8"/><path d="M0 390Q110 340 210 400T400 380V500H0Z" fill="#1f3b73" opacity=".85"/><circle cx="310" cy="70" r="26" fill="#fff" opacity=".6"/>`),
w18:sv(`<defs><linearGradient id="s18" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#ffd8a8"/><stop offset="1" stop-color="#ff9a5c"/></linearGradient></defs><rect width="400" height="500" fill="url(#s18)"/><circle cx="300" cy="140" r="50" fill="#fff4dc"/><path d="M0 320Q120 250 240 310T400 290V500H0Z" fill="#e0824a"/><path d="M0 390Q150 320 280 400T400 380V500H0Z" fill="#b95a2c"/><path d="M0 460Q140 410 260 470T400 450V500H0Z" fill="#7a3418"/>`)};
const D={w1:'ภาพทุ่งนายามพระอาทิตย์ตกในหน้าเกี่ยว แสงสีส้มอมชมพูไล่เป็นชั้นๆ บนคันนา วาดจากความทรงจำตอนกลับบ้านต่างจังหวัด เน้นซ้อนสีบางๆ หลายชั้นให้ได้แสงที่อบอุ่น',
w2:'ภาพพิมพ์แกะไม้ตรอกเก่าในย่านตลาดเก่า พิมพ์หมึกน้ำมัน 2 สี บนกระดาษสา เห็นลายไม้ธรรมชาติปรากฏในเนื้อภาพ',
w3:'ปลาคาร์ปสองตัวว่ายวนกลางบ่อยามค่ำ ตีความการเคลื่อนไหวของน้ำด้วยวงกลมซ้อนกัน วาดดิจิทัลและพิมพ์บนกระดาษ 300 แกรม สีคมชัด',
w4:'ป่าเขาในวันที่หมอกลง ใช้อะคริลิกไล่น้ำหนักจากเขียวอ่อนไปเขียวเข้ม ให้ความรู้สึกเงียบและลึก',
w5:'ลายเส้นบรรยากาศตลาดเช้า วาดด้วยปากกาหมึกดำ ไม่มีสี เน้นจังหวะของหลังคาผ้าใบและแผงผลไม้',
w6:'แมวดำนั่งใต้พระจันทร์เต็มดวง ภาพดิจิทัลโทนพาสเทลยามค่ำคืน ขนาดเล็กเหมาะแขวนหัวเตียงหรือมุมทำงาน',
w7:'ภาพถ่ายฟิล์มภูเขาสะท้อนผิวน้ำนิ่งตอนเช้า พิมพ์ Fine Art บนกระดาษผ้าฝ้าย เก็บรายละเอียดเงาสะท้อนได้ละเอียด',
w8:'ดอกบัวบานยามเช้าริมสระ สีน้ำบนกระดาษ ไล่สีชมพูอ่อนไปเข้มด้วยเทคนิคเปียกบนเปียก',
w9:'ภาพนามธรรมจากรูปทรงพื้นฐาน วงกลม สี่เหลี่ยม สามเหลี่ยม เล่นกับสีตัดกันแบบเบาเฮาส์',
w10:'แก้วกาแฟสไตล์ป๊อปอาร์ต พื้นหลังลายจุดฮาล์ฟโทน สีจัดจ้านเหมาะแขวนผนังคาเฟ่',
w11:'ภูเขาซ้อนชั้นในโทนน้ำเงิน มีดวงอาทิตย์สีส้มแดงเป็นจุดเด่น สไตล์มินิมอล',
w12:'ตึกสูงยามค่ำใต้ท้องฟ้าไล่จากม่วงเข้มเป็นชมพู หน้าต่างสีเหลืองเป็นจุดแสงเล็กๆ',
w13:'ผีเสื้อสมมาตรวาดด้วยเส้นต่อเนื่อง เน้นความเรียบง่ายและจังหวะของเส้น',
w14:'เรือใบลำเดียวกลางทะเลสงบ ท้องฟ้าโทนพีชอุ่นๆ ไล่ระดับสีด้วยเทคนิคสีน้ำ',
w15:'ทานตะวันสามดอกใต้ฟ้าสดใส ปาดสีหนาให้เห็นพื้นผิวของพู่กัน',
w16:'ลายกลีบซ้อนเป็นวงกลมแรงบันดาลใจจากลายไทย ใช้เส้นทองบนพื้นน้ำเงินเข้ม',
w17:'ภาพนามธรรมของสีที่ไหลซ้อนกัน ม่วง ชมพู เขียวมิ้นต์ และเหลือง สื่อถึงความเคลื่อนไหว',
w18:'เนินทรายซ้อนกันยามพระอาทิตย์ตก ไล่โทนส้มถึงน้ำตาลเข้ม'};
const avc=id=>{const h=[...id].reduce((a,c)=>a+c.charCodeAt(0)*37,0)%360;return`linear-gradient(135deg,hsl(${h} 70% 55%),hsl(${(h+50)%360} 70% 45%))`};
const TG={w1:'ธรรมชาติ,พระอาทิตย์ตก,ท้องนา,โทนอุ่น',w2:'เมืองเก่า,ตรอก,ภาพพิมพ์แกะไม้,วินเทจ',w3:'สัตว์,ปลา,น้ำ,โทนเย็น',w4:'ธรรมชาติ,ป่า,หมอก,โทนเย็น',w5:'ตลาด,วิถีชีวิต,ลายเส้น,ขาวดำ',w6:'สัตว์,แมว,กลางคืน,น่ารัก',w7:'ธรรมชาติ,ภูเขา,ทะเลสาบ,โทนเย็น',w8:'ดอกไม้,ดอกบัว,สีชมพู,โทนอุ่น',w9:'นามธรรม,เรขาคณิต,สีตัดกัน',w10:'ป๊อปอาร์ต,กาแฟ,สีสด',w11:'มินิมอล,ภูเขา,ธรรมชาติ,โทนเย็น',w12:'เมือง,กลางคืน,ตึก,โทนอุ่น',w13:'ผีเสื้อ,สัตว์,ลายเส้น,ขาวดำ',w14:'ทะเล,เรือใบ,พระอาทิตย์ตก,โทนอุ่น',w15:'ดอกไม้,ทานตะวัน,ธรรมชาติ,โทนอุ่น',w16:'ลายไทย,ลวดลาย,สีทอง,โทนเย็น',w17:'นามธรรม,สีสด,ลื่นไหล',w18:'ทะเลทราย,พระอาทิตย์ตก,ธรรมชาติ,โทนอุ่น'};
const HB=27;
function hsvBin(r,g,b){const mx=Math.max(r,g,b),mn=Math.min(r,g,b),v=mx/255,d=mx-mn,sat=mx?d/mx:0;if(v<.2)return 0;if(sat<.15)return v>.75?1:2;let h=d?(mx===r?((g-b)/d)%6:mx===g?(b-r)/d+2:(r-g)/d+4)*60:0;if(h<0)h+=360;return 3+Math.floor(h/30)%12*2+(v>.55?1:0)}
const normH=a=>{const t=a.reduce((x,y)=>x+y,0)||1;return a.map(x=>+(x/t).toFixed(3))};
function sigOf(id){const c={},a=Array(HB).fill(0);(SCN[id]||'').replace(/#[0-9a-fA-F]{6}/g,m=>{c[m]=(c[m]||0)+1});for(const k in c)a[hsvBin(parseInt(k.slice(1,3),16),parseInt(k.slice(3,5),16),parseInt(k.slice(5,7),16))]+=c[k];return normH(a)}
const seed=()=>({session:null,seedV:2,wish:[],cartD:[],wm:{text:'ArtCorner',op:.35},pp:'0812345678',cart:[],orders:[],logs:[],cats:[...CATS],
users:[['u1','ผู้ดูแลระบบ','admin@art.com','admin123','admin'],['u2','เจ้าหน้าที่ร้าน','staff@art.com','staff123','staff'],['u3','มะลิ ศรีสุข','mali@art.com','123456','customer','a1'],['u4','ภูมิ วงศ์ไทย','phum@art.com','123456','customer','a2'],['u5','ฟ้าใส ใจดี','fasai@art.com','123456','customer','a3'],['u6','ลูกค้าทดลอง','user@art.com','123456','customer']].map(([id,name,email,pw,role,artist])=>({id,name,email,phone:'0800000000',pass:H(pw),role,artist})),
artists:[{id:'a1',name:'มะลิ ศรีสุข',school:'คณะศิลปกรรมศาสตร์ ปี 4',bio:'ชอบวาดสีน้ำมันเกี่ยวกับธรรมชาติและแสงยามเย็น'},{id:'a2',name:'ภูมิ วงศ์ไทย',school:'คณะสถาปัตยกรรมฯ ปี 3',bio:'ภาพพิมพ์และลายเส้นเมืองเก่า'},{id:'a3',name:'ฟ้าใส ใจดี',school:'คณะมนุษยศาสตร์ ปี 2',bio:'ดิจิทัลอาร์ตสไตล์พาสเทล'}],
works:[
['w1','พระอาทิตย์ตกริมนา','a1','จิตรกรรม',3500,50,70,'สีน้ำมันบนผ้าใบ',g('#ff9a3c','#e04f9b','#3b1c6b')],
['w2','ตรอกเก่า','a2','ภาพพิมพ์',1200,30,40,'ภาพพิมพ์แกะไม้',g('#f4e3b1','#c0562b','#3a2a20')],
['w3','ปลาคาร์ปกลางฝัน','a3','ดิจิทัลอาร์ต',800,40,50,'ดิจิทัล พิมพ์บนกระดาษ 300 แกรม',g('#7be0d4','#b58cff','#1f3b73')],
['w4','ป่าหมอก','a1','จิตรกรรม',4200,60,80,'สีอะคริลิกบนผ้าใบ',g('#a7e8b5','#4a9c8c','#0f3b3b')],
['w5','ตลาดเช้า','a2','ภาพวาดเส้น',900,29,42,'ปากกาหมึกดำบนกระดาษ',g('#ffffff','#bbbbbb','#555')],
['w6','แมวกับดวงจันทร์','a3','ดิจิทัลอาร์ต',650,30,30,'ดิจิทัล พิมพ์บนกระดาษ',g('#ffe680','#8fa8ff','#2b2f6b')],
['w7','เงาสะท้อน','a1','ภาพถ่าย',1500,40,60,'ภาพถ่ายฟิล์ม พิมพ์ Fine Art',g('#9fd3ff','#f0f0f0','#324a63')],
['w8','ดอกบัวยามเช้า','a3','จิตรกรรม',2800,45,45,'สีน้ำบนกระดาษ',g('#ffc2e0','#ff6fa8','#6b2145')],
['w9','เรขาคณิตยามเช้า','a3','ดิจิทัลอาร์ต',700,30,40,'ดิจิทัล สไตล์เบาเฮาส์ พิมพ์บนกระดาษ 300 แกรม',g('#e63946','#1d3557','#f2e8d5')],
['w10','ป๊อปอาร์ตกาแฟเช้า','a3','ดิจิทัลอาร์ต',850,30,30,'ดิจิทัล พิมพ์บนกระดาษ',g('#ffe14d','#ff4d8d','#111')],
['w11','ภูเขาสองชั้น','a2','ภาพพิมพ์',1300,40,50,'ภาพพิมพ์ซิลค์สกรีน 4 สี',g('#f6d9c4','#4f6a86','#1c2a3a')],
['w12','เมืองไม่หลับ','a1','จิตรกรรม',3800,50,70,'สีอะคริลิกบนผ้าใบ',g('#14103a','#d1477a','#0c0a24')],
['w13','ผีเสื้อลายเส้น','a2','ภาพวาดเส้น',950,30,40,'ปากกาหมึกดำบนกระดาษ',g('#fbf7ee','#222','#fbf7ee')],
['w14','เรือใบยามเย็น','a1','จิตรกรรม',2600,45,60,'สีน้ำบนกระดาษ',g('#ffe9c9','#4c8fb0','#2b5f80')],
['w15','ทุ่งทานตะวัน','a1','จิตรกรรม',3200,60,80,'สีน้ำมันบนผ้าใบ',g('#9fd3ff','#ffc21a','#5c8a3a')],
['w16','ลายไทยร่วมสมัย','a2','ภาพพิมพ์',1800,40,40,'ภาพพิมพ์ฟอยล์ทองบนกระดาษสีน้ำเงิน',g('#1b2a4a','#e5b93c','#1b2a4a')],
['w17','สายน้ำนามธรรม','a1','จิตรกรรม',4500,70,90,'สีอะคริลิกเทและปาดบนผ้าใบ',g('#5b3df5','#e04f9b','#1f3b73')],
['w18','แสงบนเนินทราย','a1','ภาพถ่าย',1700,40,60,'ภาพถ่ายดิจิทัล พิมพ์ Fine Art',g('#ffd8a8','#e0824a','#7a3418')]
].map(([id,title,artist,cat,price,w,h,tech,gr])=>({id,title,artist,cat,price,w,h,tech,g:gr,svg:id,tags:(TG[id]||'').split(',').filter(Boolean),sig:sigOf(id),desc:D[id],digital:{price:Math.max(199,Math.round(price*.12/10)*10),w:3200,h:4000,fmt:'PNG'},status:'available',approval:'approved'}))});
let db;try{db=JSON.parse(localStorage.getItem(K))}catch(e){}if(!db)db=seed();db.apps=db.apps||[];db.wish=db.wish||[];db.cartD=db.cartD||[];db.coms=db.coms||[];initSocial();db.wm=db.wm||{text:'ArtCorner',op:.35};if((db.seedV||1)<2){seed().works.filter(w=>+w.id.slice(1)>8).forEach(w=>db.works.push(w));db.seedV=2}seed().works.forEach(sw=>{const w=db.works.find(x=>x.id===sw.id);if(w&&!w.svg&&!w.img){w.svg=sw.svg;w.desc=sw.desc}if(w&&!w.img&&!w.digital&&sw.digital)w.digital=sw.digital;if(w&&!w.img&&!w.tags){w.tags=sw.tags;w.sig=sw.sig}});
const save=()=>{if(REMOTE){persistLocal();Q=Q.then(push).catch(()=>{});return}try{localStorage.setItem(K,JSON.stringify(db))}catch(e){toast('พื้นที่เก็บข้อมูลเต็ม')}};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const baht=n=>'฿'+Number(n).toLocaleString('th-TH');
const W=id=>db.works.find(w=>w.id===id),A=id=>db.artists.find(a=>a.id===id);
const me=()=>db.users.find(u=>u.id===db.session),R=()=>me()?.role||'guest';
const isAd=()=>R()==='admin',isMgr=()=>isAd()||R()==='staff',isA=()=>!!me()?.artist;
const shipList=()=>{const k=me()?.artist;return k?db.orders.filter(o=>o.uid!==db.session&&!o.cancelled&&o.status>=1&&o.items.some(i=>W(i)?.artist===k)):[]},RATE=()=>db.comm??10,cutOf=b=>Math.floor(b*RATE()/100+.5),rentUntil=()=>A(me()?.artist)?.until,rentOk=()=>{const u=rentUntil();return u==null||u>=Date.now()},dTH=t=>new Date(t).toLocaleDateString('th-TH');
function toast(m){const t=$('#toast');t.textContent=m;t.className='s';setTimeout(()=>t.className='',2000)}
const art=(w,nw)=>`<div class="th">${w.img?`<img src="${w.img}" alt="${esc(w.title)}" loading="lazy">`:SCN[w.svg]?`<div class="ph">${SCN[w.svg]}</div>${nw?'':`<div class="wm" style="background-image:${wmBg()}"></div>`}`:`<div class="ph" style="background:radial-gradient(circle at 30% 30%,${w.g[0]},transparent 55%),radial-gradient(circle at 75% 70%,${w.g[1]},transparent 50%),${w.g[2]}"></div>`}</div>`;
const stTag=w=>w.approval==='pending'?'<span class="tag w">รออนุมัติ</span>':w.approval==='rejected'?'<span class="tag bad">ไม่ผ่าน</span>':w.status==='sold'?'<span class="tag bad">ขายแล้ว</span>':'<span class="tag ok">ยังว่าง</span>';
function burn(c,t,o){const x=c.getContext('2d'),fs=Math.max(16,Math.round(c.width/24));x.save();x.font=`700 ${fs}px "Noto Sans Thai",sans-serif`;x.textAlign='center';x.textBaseline='middle';x.fillStyle=`rgba(255,255,255,${o})`;x.strokeStyle=`rgba(0,0,0,${o*.55})`;x.lineWidth=Math.max(1,fs/16);
const sx=x.measureText(t).width+fs*2,sy=fs*3.6,d=Math.hypot(c.width,c.height);x.translate(c.width/2,c.height/2);x.rotate(-Math.PI/6);
for(let r=0,yy=-d;yy<d;yy+=sy,r++)for(let xx=-d+(r%2)*sx/2;xx<d;xx+=sx){x.strokeText(t,xx,yy);x.fillText(t,xx,yy)}x.restore()}
function resize(file,max,cb,wm,sg){const r=new FileReader();r.onload=()=>{const i=new Image();i.onload=()=>{const k=Math.min(1,max/Math.max(i.width,i.height)),c=document.createElement('canvas');c.width=i.width*k;c.height=i.height*k;c.getContext('2d').drawImage(i,0,0,c.width,c.height);if(sg)sg.v=histOf(c);if(wm)burn(c,wm,db.wm.op);cb(c.toDataURL('image/jpeg',.82))};i.src=r.result};r.readAsDataURL(file)}
const rz=(f,m,wm,sg)=>new Promise(r=>resize(f,m,r,wm,sg));
const dimOf=f=>new Promise((res,rej)=>{const u=URL.createObjectURL(f),i=new Image();i.onload=()=>{res({w:i.naturalWidth,h:i.naturalHeight});URL.revokeObjectURL(u)};i.onerror=rej;i.src=u});
let _wk='',_wv='';
function wmBg(){const t=db.wm.text,o=db.wm.op,k=t+o;if(k!==_wk){const v=`<svg xmlns='http://www.w3.org/2000/svg' width='240' height='150'><text x='120' y='75' transform='rotate(-28 120 75)' text-anchor='middle' font-family='sans-serif' font-size='20' font-weight='700' fill='white' fill-opacity='${o}' stroke='black' stroke-opacity='${o*.5}' stroke-width='.7'>${esc(t)}</text></svg>`;_wv='url('+encodeURIComponent(v).replace(/'/g,'%27').replace(/\(/g,'%28').replace(/\)/g,'%29').replace(/^/,'data:image/svg+xml,')+')';_wk=k}return _wv}
const idb=()=>new Promise((res,rej)=>{const r=indexedDB.open('artcorner',1);r.onupgradeneeded=()=>r.result.createObjectStore('hi');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const hiPut=async(k,b)=>{const d=await idb();return new Promise((res,rej)=>{const t=d.transaction('hi','readwrite');t.objectStore('hi').put(b,k);t.oncomplete=res;t.onerror=()=>rej(t.error)})};
const hiGet=async k=>{const d=await idb();return new Promise((res,rej)=>{const q=d.transaction('hi').objectStore('hi').get(k);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})};
const hiDel=async k=>{const d=await idb();return new Promise(res=>{const t=d.transaction('hi','readwrite');t.objectStore('hi').delete(k);t.oncomplete=res;t.onerror=res})};
const svgPng=w=>new Promise((res,rej)=>{const a=w.digital.w,b=w.digital.h,v=SCN[w.svg].replace(/ style="[^"]*"/,'').replace('<svg ',`<svg xmlns="http://www.w3.org/2000/svg" width="${a}" height="${b}" `),i=new Image();i.onload=()=>{const c=document.createElement('canvas');c.width=a;c.height=b;c.getContext('2d').drawImage(i,0,0,a,b);c.toBlob(x=>x?res(x):rej(),'image/png')};i.onerror=rej;i.src=URL.createObjectURL(new Blob([v],{type:'image/svg+xml'}))});
async function dlFile(id){const w=W(id);if(!w?.digital)return;const ok=isMgr()||(isA()&&w.artist===me().artist)||db.orders.some(o=>o.uid===db.session&&!o.cancelled&&o.status>=1&&(o.dl||[]).includes(id));
if(!ok)return toast('ยังไม่มีสิทธิ์ดาวน์โหลด — ต้องชำระเงินและรอการยืนยันก่อน');
try{let b;if(w.digital.file){b=await hiGet(id);if(!b)return toast('ไม่พบไฟล์ในเบราว์เซอร์นี้ (เดโม: ไฟล์เก็บไว้ในเครื่องที่อัปโหลด)')}else b=await svgPng(w);
const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${w.title}-${w.digital.w}x${w.digital.h}.${w.digital.file?(w.digital.fmt||'jpg').toLowerCase().replace('jpeg','jpg'):'png'}`;document.body.appendChild(a);a.click();a.remove();toast('เริ่มดาวน์โหลดแล้ว')}catch(e){toast('ดาวน์โหลดไม่สำเร็จ')}}
const cartTotal=()=>db.cart.map(W).filter(w=>w&&w.status==='available'&&!isMine(w)).reduce((a,w)=>a+w.price,0)+db.cartD.map(W).filter(w=>w&&w.digital&&!isMine(w)).reduce((a,w)=>a+w.digital.price,0);
function addDigital(id){const w0=W(id);if(w0&&isMine(w0))return toast('ซื้อผลงานของตัวเองไม่ได้');if(!db.cartD.includes(id))db.cartD.push(id);save();toast('เพิ่มไฟล์ดิจิทัลลงตะกร้าแล้ว');go()}
const WMBOX=()=>`<div class="box" style="max-width:420px"><label>ข้อความลายน้ำ (ประทับบนรูปตัวอย่างอัตโนมัติ)</label><input id="wt" value="${esc(db.wm.text)}"><label>ความเข้มลายน้ำ (10–60%)</label><input id="wo" type="number" value="${Math.round(db.wm.op*100)}"><div class="err" id="werr"></div><br><button class="btn" onclick="saveWM()">บันทึก</button><p class="mu">มีผลกับรูปที่อัปโหลดหลังจากนี้ รูปเดิมที่อัปโหลดไว้แล้วต้องอัปโหลดใหม่</p></div>`;
function saveWM(){const t=val('wt'),o=+val('wo');if(!chk('werr',[[t.length<2||t.length>30,'ข้อความลายน้ำ 2–30 ตัวอักษร'],[!Number.isInteger(o)||o<10||o>60,'ความเข้มเป็นจำนวนเต็ม 10–60']]))return;log('แก้ไข','ตั้งค่า','ลายน้ำ',db.wm.text+' '+Math.round(db.wm.op*100)+'% → '+t+' '+o+'%');db.wm={text:t,op:o/100};save();toast('บันทึกแล้ว');go()}
function pp(id,amt){const t=(k,v)=>k+String(v.length).padStart(2,'0')+v;id=id.replace(/\D/g,'');const acc=id.length>=13?t('02',id):t('01','0066'+id.slice(1));
let s=t('00','01')+t('01','12')+t('29',t('00','A000000677010111')+acc)+t('53','764')+t('54',amt.toFixed(2))+t('58','TH')+'6304',c=0xFFFF;
for(const ch of s){c^=ch.charCodeAt(0)<<8;for(let i=0;i<8;i++)c=c&0x8000?((c<<1)^0x1021)&0xFFFF:(c<<1)&0xFFFF}return s+c.toString(16).toUpperCase().padStart(4,'0')}
const ROLE={admin:'แอดมิน',staff:'เจ้าหน้าที่',customer:'ลูกค้า'},AP={pending:'รออนุมัติ',approved:'อนุมัติแล้ว',rejected:'ไม่ผ่าน'};
const PS=10,GS=8,EM=/^[^\s@]+@[^\s@]+\.[^\s@]+$/,PH=/^0\d{9}$/;
const val=id=>($('#'+id)?.value||'').trim();
function chk(id,rules){const m=rules.filter(r=>r[0]).map(r=>'• '+r[1]);const e=$('#'+id);if(e)e.innerHTML=m.join('<br>');return !m.length}
const df=(a,b,ks)=>ks.filter(k=>a[k]!==b[k]).map(k=>`${k}: ${a[k]}→${b[k]}`).join(', ');
function log(act,ent,id,d=''){db.logs.unshift({i:'L'+Date.now().toString(36)+Math.random().toString(36).slice(2,5),t:new Date().toLocaleString('th-TH'),u:me()?.email||'-',r:R(),act,ent,id,d});db.logs=db.logs.slice(0,500)}
const to=h=>{location.hash=h;go()};
function pager(n,p,js,s=PS){const c=Math.ceil(n/s);if(c<2)return'';let b='';for(let i=0;i<c;i++)b+=`<button class="${i===p?'on':''}" onclick="${js.replace('#',i)}">${i+1}</button>`;return`<div class="pg">${b}<span class="mu">${n} รายการ</span></div>`}
const DT={};
function dt(id,rows,cols,o={}){const s=DT[id]=Object.assign(DT[id]||{q:'',k:-1,d:1,p:0,fv:''},{rows,cols,o});post.push(()=>drawDT(id));
return`<div class="box"><div class="row"><span class="sb">${MG}<input placeholder="ค้นหา" value="${esc(s.q)}" oninput="DT['${id}'].q=this.value;DT['${id}'].p=0;drawDT('${id}')" style="max-width:260px"></span>${o.fk?`<select style="width:auto" onchange="DT['${id}'].fv=this.value;DT['${id}'].p=0;drawDT('${id}')"><option value="">ทั้งหมด</option>${o.fo.map(x=>`<option ${s.fv===x?'selected':''}>${esc(x)}</option>`).join('')}</select>`:''}</div><div id="dt-${id}" style="overflow-x:auto"></div></div>`}
function drawDT(id){const s=DT[id],el=$('#dt-'+id);if(!el)return;const q=s.q.toLowerCase();
let l=s.rows.filter(r=>(!s.fv||s.o.fk(r)===s.fv)&&(!q||s.cols.map(c=>c.t(r)).join(' ').toLowerCase().includes(q)));
if(s.k>=0){const t=s.cols[s.k].t;l.sort((a,b)=>(t(a)>t(b)?1:t(a)<t(b)?-1:0)*s.d)}
s.p=Math.min(s.p,Math.max(0,Math.ceil(l.length/PS)-1));
el.innerHTML=`<table class="dt"><tr>${s.cols.map((c,i)=>`<th onclick="sortDT('${id}',${i})">${c.h}${s.k===i?(s.d>0?' ▲':' ▼'):''}</th>`).join('')}</tr>${l.slice(s.p*PS,s.p*PS+PS).map(r=>`<tr>${s.cols.map(c=>`<td>${c.f?c.f(r):esc(c.t(r))}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${s.cols.length}" class="mu">ไม่พบข้อมูล</td></tr>`}</table>${pager(l.length,s.p,`DT['${id}'].p=#;drawDT('${id}')`)}`}
function sortDT(id,i){const s=DT[id];s.d=s.k===i?-s.d:1;s.k=i;drawDT(id)}
const MG='<svg class="mg" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="M15.5 15.5L21 21"/></svg>';
function nav(){const u=me(),tot=cartTotal();
const pend=db.apps.filter(a=>a.status==='pending').length+db.works.filter(w=>w.approval==='pending').length+db.orders.filter(o=>!o.cancelled&&o.status===0&&o.slip).length;
const dd=(t,m)=>`<div class="dd"><a tabindex="0">${t} ▾</a><div class="menu">${m}</div></div>`;
const acct=u?dd(esc(u.name),`<a href="#/profile">โปรไฟล์</a><a href="#/orders">คำสั่งซื้อ</a><a href="#/jobs">งานจ้างวาด</a><a href="#/following">ศิลปินที่ติดตาม (${db.follows.filter(f=>f.u===db.session).length})</a>${isA()?'<a href="#/upload">＋ อัปโหลดผลงาน</a><a href="#/apply">💳 ค่าพื้นที่ขาย'+(rentOk()?'':' (หมดอายุ)')+'</a><a href="#/ship">📦 ออเดอร์ที่ต้องส่ง'+(n=>n?' ('+n+')':'')(shipList().filter(o=>o.status===1&&!o.ships?.[me().artist]).length)+'</a>':''}${u.role==='customer'&&!u.artist?'<a href="#/apply">🎨 สมัครเป็นศิลปิน</a>':''}${isMgr()?`<a href="#/admin">หลังบ้าน${pend?` (${pend})`:''}</a>`:''}<a href="#/" onclick="logout();return false">ออกจากระบบ</a>`):'<a href="#/login">เข้าสู่ระบบ</a>';
$('#hd').innerHTML=`<nav class="hl">${dd('ผลงาน',db.cats.map(c=>`<a href="#/" data-v="${esc(c)}" onclick="shop('cat',this.dataset.v);return false">${esc(c)}</a>`).join('')+`<a href="#/" onclick="shop('cat','');return false"><b>ดูทั้งหมด</b></a>`)}<a href="#/hire">จ้างวาดรูป</a><span class="sb">${MG}<input id="hs" class="hs" list="al" placeholder="ค้นหาศิลปิน / ผลงาน" value="${esc(F.q)}" onkeydown="if(event.key==='Enter')hsearch()"></span><datalist id="al">${db.artists.map(a=>`<option value="${esc(a.name)}">`).join('')}</datalist></nav>
<a class="lg" href="#/" aria-label="ArtCorner"><svg viewBox="0 0 48 48" width="52" height="52"><circle cx="24" cy="24" r="22" fill="none" stroke="#111" stroke-width="3"/><circle cx="24" cy="24" r="16" fill="none" stroke="#e63946" stroke-width="3"/><circle cx="24" cy="24" r="10" fill="none" stroke="#2ab7b0" stroke-width="3"/><circle cx="24" cy="24" r="4.5" fill="#111"/></svg></a>
<nav class="hr">${acct}<a href="#/wishlist">ถูกใจ <span style="color:#e63946">♥</span>${db.likes.filter(l=>l.u===db.session).length?' '+db.likes.filter(l=>l.u===db.session).length:''}</a><a class="ct" href="#/cart">ตะกร้า / ${baht(tot)} <span class="cnt">${db.cart.length+db.cartD.length}</span></a></nav>`}
async function afterAuth(r){TOK=r.token;db.session=r.user.id;persistLocal();V=null;LAST='';await pull(true,true)}
async function doLogin(){const e=val('le').toLowerCase(),pw=$('#lp').value;
if(REMOTE){if(!chk('lerr',[[!e||!pw,'กรอกอีเมลและรหัสผ่าน']]))return;const r=await api('login',{email:e,password:pw});if(!chk('lerr',[[!r.ok,r.err||'เข้าสู่ระบบไม่สำเร็จ']]))return;await afterAuth(r);toast('ยินดีต้อนรับ '+r.user.name);to(isMgr()?'#/admin':'#/');return}
const u=db.users.find(x=>x.email===e&&x.pass===H(pw));
if(!chk('lerr',[[!e||!pw,'กรอกอีเมลและรหัสผ่าน'],[e&&pw&&!u,'อีเมลหรือรหัสผ่านไม่ถูกต้อง']]))return;
db.session=u.id;save();toast('ยินดีต้อนรับ '+u.name);to(isMgr()?'#/admin':'#/')}
async function doReg(){const n=val('rn'),e=val('re').toLowerCase(),p=val('rp'),w=$('#rw').value,art=$('#ra').checked;
if(!chk('rerr',[[n.length<2,'ชื่ออย่างน้อย 2 ตัวอักษร'],[!EM.test(e),'รูปแบบอีเมลไม่ถูกต้อง'],[!REMOTE&&db.users.some(u=>u.email===e),'อีเมลนี้ถูกใช้แล้ว'],[!PH.test(p),'เบอร์โทรต้องเป็นตัวเลข 10 หลักขึ้นต้นด้วย 0'],[w.length<6,'รหัสผ่านอย่างน้อย 6 ตัวอักษร'],[w!==$('#rc').value,'รหัสผ่านไม่ตรงกัน']]))return;
if(REMOTE){const r=await api('register',{name:n,email:e,phone:p,password:w});if(!chk('rerr',[[!r.ok,r.err||'สมัครสมาชิกไม่สำเร็จ']]))return;await afterAuth(r);toast('สมัครสมาชิกสำเร็จ');to(art?'#/apply':'#/');return}
const u={id:'u'+Date.now(),name:n,email:e,phone:p,pass:H(w),role:'customer'};
db.users.push(u);db.session=u.id;log('สมัครสมาชิก','ผู้ใช้',u.id,e);save();toast('สมัครสมาชิกสำเร็จ');to(art?'#/apply':'#/')}
function logout(){if(REMOTE){TOK='';db.session=null;['orders','coms','apps','logs'].forEach(c=>db[c]=[]);db.users=db.users.map(u=>({id:u.id,name:u.name,artist:u.artist}));snapshot();persistLocal();V=null;Q=Q.then(()=>pull(true,true));to('#/');return}db.session=null;save();to('#/')}
async function saveProfile(){const u=me(),a=u.artist&&A(u.artist),n=val('pn'),p=val('pp2'),pw=$('#pw').value;
if(!chk('perr',[[n.length<2,'ชื่ออย่างน้อย 2 ตัวอักษร'],[p&&!PH.test(p),'เบอร์โทรต้องเป็นตัวเลข 10 หลัก'],[pw&&pw.length<6,'รหัสผ่านใหม่อย่างน้อย 6 ตัวอักษร'],[REMOTE&&pw&&!$('#po').value,'กรอกรหัสผ่านเดิมเพื่อเปลี่ยนรหัสผ่าน'],[a&&val('ps').length<2,'กรอกคณะ/สถาบัน'],[a&&val('pb').length>300,'แนะนำตัวไม่เกิน 300 ตัวอักษร']]))return;
if(REMOTE&&pw){const r=await api('passwd',{oldPassword:$('#po').value,newPassword:pw});if(!chk('perr',[[!r.ok,r.err||'เปลี่ยนรหัสผ่านไม่สำเร็จ']]))return}
const o={name:u.name,phone:u.phone};u.name=n;u.phone=p;if(pw&&!REMOTE)u.pass=H(pw);
if(a){a.name=n;a.school=val('ps');a.bio=val('pb')}
log('แก้ไข','โปรไฟล์',u.id,df(o,u,['name','phone'])+(pw?' เปลี่ยนรหัสผ่าน':''));save();toast('บันทึกแล้ว');go()}
const canEdit=w=>isMgr()||(isA()&&w.artist===me().artist);
const fw=w=>`<div class="box" style="max-width:520px"><h2>${w?'แก้ไข':'อัปโหลด'}ผลงาน</h2>${w&&!isMgr()?'<p class="mu">หลังแก้ไข ผลงานจะกลับไปรอแอดมินอนุมัติอีกครั้ง</p>':''}<label>รูปผลงาน${w?' (เว้นว่างถ้าไม่เปลี่ยน)':''}</label><input id="uf" type="file" accept="image/*"><label>ชื่อผลงาน</label><input id="ut" value="${esc(w?.title)}"><label>หมวด</label><select id="uc">${db.cats.map(c=>`<option ${w?.cat===c?'selected':''}>${esc(c)}</option>`).join('')}</select>
<div class="row"><div class="grow"><label>กว้าง (ซม.)</label><input id="uw" type="number" value="${w?.w||''}"></div><div class="grow"><label>สูง (ซม.)</label><input id="uh" type="number" value="${w?.h||''}"></div><div class="grow"><label>ราคา (บาท)</label><input id="upr" type="number" value="${w?.price||''}"></div></div><label>เทคนิค/วัสดุ</label><input id="ux" value="${esc(w?.tech)}"><label>เรื่องราว/รายละเอียดผลงาน (10–500 ตัวอักษร)</label><textarea id="ud" rows="4">${esc(w?.desc)}</textarea><label>แท็ก (คั่นด้วยจุลภาค สูงสุด 8 แท็ก เช่น ธรรมชาติ, โทนอุ่น) — ใช้แนะนำผลงานที่คล้ายกัน</label><input id="ug" value="${esc((w?.tags||[]).join(', '))}"><label style="display:flex;gap:8px;align-items:center;margin-top:12px"><input type="checkbox" id="dg" style="width:auto" ${w?.digital?'checked':''} onchange="$('#dgf').style.display=this.checked?'block':'none'"> ขายไฟล์ดิจิทัลความละเอียดสูงด้วย</label><div id="dgf" style="display:${w?.digital?'block':'none'}"><label>ราคาไฟล์ดิจิทัล (บาท)</label><input id="dpr" type="number" value="${w?.digital?.price||''}"><label>ไฟล์ความละเอียดสูง JPG/PNG/WebP (ด้านยาว ≥ 1,500 พิกเซล) — ถ้าไม่เลือก จะใช้ไฟล์รูปผลงานด้านบน</label><input id="dhf" type="file" accept="image/jpeg,image/png,image/webp"></div><div class="err" id="ue"></div><br><button class="btn" onclick="saveWork('${w?.id||''}')">บันทึก</button></div>`;
async function saveWork(id){const f=$('#uf').files[0],t=val('ut'),p=+val('upr'),wd=+val('uw'),h=+val('uh'),x=val('ux'),c=val('uc'),d=val('ud'),dg=$('#dg').checked,dp=+val('dpr'),hf=$('#dhf').files[0]||f,old=id?W(id):null,tg=[...new Set(val('ug').split(/[,，]/).map(x=>x.trim()).filter(Boolean))];
if(!chk('ue',[[!id&&!f,'กรุณาเลือกรูปผลงาน'],[f&&!/^image\//.test(f.type),'ไฟล์ต้องเป็นรูปภาพ'],[f&&f.size>10e6,'รูปตัวอย่างต้องไม่เกิน 10 MB'],[t.length<2||t.length>80,'ชื่อผลงาน 2–80 ตัวอักษร'],[!db.cats.includes(c),'หมวดไม่ถูกต้อง'],[!(wd>=1&&wd<=300&&h>=1&&h<=300),'ขนาดต้องอยู่ระหว่าง 1–300 ซม.'],[!Number.isInteger(p)||p<1||p>1e6,'ราคาเป็นจำนวนเต็ม 1–1,000,000 บาท'],[x.length>100,'เทคนิคยาวเกิน 100 ตัวอักษร'],[d.length<10||d.length>500,'รายละเอียดผลงาน 10–500 ตัวอักษร'],
[dg&&!(Number.isInteger(dp)&&dp>=50&&dp<=100000),'ราคาไฟล์ดิจิทัลเป็นจำนวนเต็ม 50–100,000 บาท'],[dg&&!hf&&!old?.digital,'กรุณาเลือกไฟล์ความละเอียดสูง'],[dg&&hf&&!['image/jpeg','image/png','image/webp'].includes(hf.type),'ไฟล์ความละเอียดสูงต้องเป็น JPG, PNG หรือ WebP'],[dg&&hf&&hf.size>40e6,'ไฟล์ความละเอียดสูงต้องไม่เกิน 40 MB'],[tg.length>8,'แท็กไม่เกิน 8 แท็ก'],[tg.some(x=>x.length<2||x.length>20),'แต่ละแท็กต้องยาว 2–20 ตัวอักษร']]))return;
const nid=id||'w'+Date.now();let dgv=old?.digital||null,put=false;
if(dg&&hf){let m;try{m=await dimOf(hf)}catch(e){chk('ue',[[1,'อ่านไฟล์ความละเอียดสูงไม่ได้']]);return}
 if(!chk('ue',[[Math.max(m.w,m.h)<1500,`ไฟล์ความละเอียดสูงต้องมีด้านยาวอย่างน้อย 1,500 พิกเซล (ไฟล์นี้ ${m.w}×${m.h})`]]))return;
 dgv={price:dp,w:m.w,h:m.h,fmt:hf.type.split('/')[1].toUpperCase().replace('JPEG','JPG'),size:hf.size,file:true};put=true}
else if(dg&&dgv)dgv={...dgv,price:dp};else dgv=null;
if(put){try{await hiPut(nid,hf)}catch(e){toast('บันทึกไฟล์ความละเอียดสูงไม่สำเร็จ');return}}
else if(!dg&&old?.digital?.file)hiDel(nid).catch(()=>{});
const an=A(old?old.artist:me().artist)?.name||'',sg={},img=f?await rz(f,800,db.wm.text+(an?' • '+an:''),sg):undefined;
if(id){const w=old,o={...w};Object.assign(w,{title:t,cat:c,price:p,w:wd,h,tech:x,desc:d,digital:dgv,tags:tg});if(img){w.img=img;w.sig=sg.v}if(!isMgr())w.approval='pending';log('แก้ไข','ผลงาน',id,(df(o,w,['title','cat','price','w','h','tech','desc'])||'เปลี่ยนรูป')+(o.digital?.price!==dgv?.price?`, ไฟล์ดิจิทัล: ${o.digital?.price??'ไม่ขาย'}→${dgv?.price??'ไม่ขาย'}`:''));toast('บันทึกแล้ว')}
else{const n={id:nid,title:t,artist:me().artist,cat:c,price:p,w:wd,h,tech:x||'-',desc:d,img,sig:sg.v,tags:tg,digital:dgv,status:'available',approval:'pending'};db.works.push(n);log('เพิ่ม','ผลงาน',nid,t+(dgv?` (ขายไฟล์ดิจิทัล ${dgv.price})`:''));toast('ส่งงานแล้ว รอแอดมินอนุมัติ')}
save();to(id?'#/work/'+id:'#/artist/'+me().artist)}
function delWork(id){const w=W(id);if(!canEdit(w))return;if(db.orders.some(o=>!o.cancelled&&(o.items.includes(id)||(o.dl||[]).includes(id))))return toast('ลบไม่ได้: ผลงานอยู่ในคำสั่งซื้อ');
if(!confirm('ลบผลงาน “'+w.title+'” ?'))return;db.likes=db.likes.filter(l=>l.w!==id);db.reviews=db.reviews.filter(r=>!(r.kind==='w'&&r.ref===id));if(w.digital?.file)hiDel(id).catch(()=>{});db.works=db.works.filter(x=>x.id!==id);db.cartD=db.cartD.filter(x=>x!==id);db.cart=db.cart.filter(x=>x!==id);log('ลบ','ผลงาน',id,w.title);save();toast('ลบแล้ว');to('#/')}
const F={q:'',cat:'',artist:'',min:'',max:'',sort:'new'};
const P={};let post=[];
P.home=()=>`${heroHTML()}${sec('ผลงานมาใหม่')}
<div class="bar" id="shop"><span class="sb">${MG}<input placeholder="ค้นหาชื่อผลงานหรือศิลปิน" value="${esc(F.q)}" oninput="F.q=this.value;F.page=0;drawGrid()"></span>
<select onchange="F.cat=this.value;F.page=0;drawGrid()"><option value="">ทุกหมวด</option>${db.cats.map(c=>`<option ${F.cat===c?'selected':''}>${c}</option>`).join('')}</select>
<select onchange="F.artist=this.value;F.page=0;drawGrid()"><option value="">ทุกศิลปิน</option>${db.artists.map(a=>`<option value="${a.id}" ${F.artist===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select>
<input type="number" placeholder="ราคาต่ำสุด" value="${F.min}" oninput="F.min=this.value;F.page=0;drawGrid()"><input type="number" placeholder="ราคาสูงสุด" value="${F.max}" oninput="F.max=this.value;F.page=0;drawGrid()">
<select onchange="F.sort=this.value;F.page=0;drawGrid()"><option value="new">ใหม่สุด</option><option value="lo" ${F.sort==='lo'?'selected':''}>ราคาต่ำ → สูง</option><option value="hi" ${F.sort==='hi'?'selected':''}>ราคาสูง → ต่ำ</option><option value="like" ${F.sort==='like'?'selected':''}>ถูกใจมากสุด</option><option value="rate" ${F.sort==='rate'?'selected':''}>คะแนนรีวิวสูงสุด</option></select></div><div id="grid" class="grid"></div><div id="pgr"></div>${recHome()}`;
function drawGrid(an){const g=$('#grid');if(!g)return;g.classList&&g.classList.toggle('anim',!!an);let l=db.works.filter(w=>w.approval==='approved'&&(!F.q||(w.title+' '+(A(w.artist)?.name||'')+' '+(w.tags||[]).join(' ')).toLowerCase().includes(F.q.toLowerCase()))&&(!F.cat||w.cat===F.cat)&&(!F.artist||w.artist===F.artist)&&(!F.min||w.price>=+F.min)&&(!F.max||w.price<=+F.max));
if(F.sort==='lo')l.sort((a,b)=>a.price-b.price);else if(F.sort==='hi')l.sort((a,b)=>b.price-a.price);else if(F.sort==='like')l.sort((a,b)=>lc(b.id)-lc(a.id));else if(F.sort==='rate')l.sort((a,b)=>avgW(b.id)-avgW(a.id)||rcW(b.id)-rcW(a.id));else l.reverse();
F.page=Math.min(F.page||0,Math.max(0,Math.ceil(l.length/GS)-1));g.innerHTML=l.slice(F.page*GS,F.page*GS+GS).map(w=>wc(w)).join('')||'<p class="mu">ไม่พบผลงานตามเงื่อนไข</p>';$('#pgr').innerHTML=pager(l.length,F.page,'F.page=#;drawGrid(1)',GS)}
P.work0=id=>{const w=W(id);if(!w)return'<p>ไม่พบผลงาน</p>';const a=A(w.artist),inC=db.cart.includes(id),mine=isMine(w),ok=w.status==='available'&&w.approval==='approved'&&!mine;
return`<div class="two"><div class="card">${art(w)}</div><div><h1>${esc(w.title)}</h1><p>โดย <a href="#/artist/${a.id}" style="color:var(--ac)">${esc(a.name)}</a> · ${esc(a.school)}</p>
<table><tr><td>หมวด</td><td>${w.cat}</td></tr><tr><td>ขนาด</td><td>${w.w} × ${w.h} ซม.</td></tr><tr><td>เทคนิค</td><td>${esc(w.tech)}</td></tr><tr><td>ประเภท</td><td>ผลงานต้นฉบับ 1 ชิ้น (ไม่มีสำเนา)</td></tr><tr><td>การจัดส่ง</td><td>ห่อกันกระแทก ส่งภายใน 3–5 วันทำการ (ไม่รวมกรอบ)</td></tr><tr><td>สถานะ</td><td>${stTag(w)}</td></tr></table>
${w.desc?`<h3>เรื่องราวของผลงาน</h3><p>${esc(w.desc)}</p>`:''}<h2>${baht(w.price)}</h2><div class="row"><button class="btn" ${ok&&!inC?'':'disabled'} onclick="addCart('${id}')">${mine?'ผลงานของคุณ':inC?'อยู่ในตะกร้าแล้ว':ok?'เพิ่มลงตะกร้า':'ไม่พร้อมขาย'}</button><a class="btn o" href="#/cart">ดูตะกร้า</a>${canEdit(w)?`<a class="btn o" href="#/edit/${id}">แก้ไข</a><button class="btn r" onclick="delWork('${id}')">ลบ</button>`:''}</div></div></div>`};
function addCart(id){const w0=W(id);if(w0&&isMine(w0))return toast('ซื้อผลงานของตัวเองไม่ได้');if(!db.cart.includes(id))db.cart.push(id);save();toast('เพิ่มลงตะกร้าแล้ว');go()}
P.artist0=id=>{const a=A(id);if(!a)return'<p>ไม่พบศิลปิน</p>';const mine=me()?.artist===id;
const l=db.works.filter(w=>w.artist===id&&(w.approval==='approved'||mine||isMgr()));
return`<div class="box"><div class="row"><span class="av" style="background:${avc(a.id)}">${esc([...a.name][0])}</span><h1 class="grow">${esc(a.name)}</h1></div><div class="mu">${esc(a.school)}</div><p>${esc(a.bio)}</p>${mine?`<a class="btn" href="#/upload">＋ อัปโหลดผลงานใหม่</a>`:''}${!mine&&me()&&a.id!==me().artist?`<a class="btn o" href="#/hire/${a.id}">จ้างศิลปินคนนี้วาดรูป</a>`:''}</div><h2>ผลงาน (${l.length})</h2><div class="grid">${l.map(w=>wc(w)).join('')}</div>`};
P.cart=()=>{const l=db.cart.map(W).filter(w=>w&&w.status==='available'&&!isMine(w)),d=db.cartD.map(W).filter(w=>w&&w.digital&&w.approval==='approved'&&!isMine(w)),s1=l.reduce((a,w)=>a+w.price,0),s2=d.reduce((a,w)=>a+w.digital.price,0),sh=l.length?SHIP:0;
if(!l.length&&!d.length)return'<h2>ตะกร้าว่าง</h2><a class="btn" href="#/">เลือกชมผลงาน</a>';
const row=(w,p,tag,rm)=>`<div class="box row"><div class="mini">${art(w)}</div><div class="grow"><b>${esc(w.title)}</b> <span class="tag">${tag}</span><div class="mu">${esc(A(w.artist)?.name)}</div></div><b>${baht(p)}</b><button class="btn o" onclick="${rm}">ลบ</button></div>`;
return`<h2>ตะกร้าสินค้า</h2><div class="two"><div>${l.map(w=>row(w,w.price,'ผลงานต้นฉบับ',`db.cart=db.cart.filter(x=>x!=='${w.id}');save();go()`)).join('')}${d.map(w=>row(w,w.digital.price,'ไฟล์ดิจิทัล',`db.cartD=db.cartD.filter(x=>x!=='${w.id}');save();go()`)).join('')}</div>
<div class="box"><h3>${l.length?'ที่อยู่จัดส่ง':'ข้อมูลผู้ซื้อ'}</h3><label>ชื่อผู้รับ</label><input id="cn" value="${esc(me()?.name)}"><label>เบอร์โทร</label><input id="cp" value="${esc(me()?.phone)}">${l.length?'<label>ที่อยู่</label><textarea id="ca" rows="3"></textarea>':''}<div class="err" id="ce"></div>
<p>${l.length?`ผลงานต้นฉบับ ${baht(s1)}<br>ค่าจัดส่ง ${baht(sh)}<br>`:''}${d.length?`ไฟล์ดิจิทัล ${baht(s2)} <span class="mu">(ไม่มีค่าจัดส่ง)</span><br>`:''}<b>รวม ${baht(s1+s2+sh)}</b></p><button class="btn" onclick="checkout()">สั่งซื้อและไปชำระเงิน</button></div></div>`};
function checkout(){const l=db.cart.map(W).filter(w=>w&&w.status==='available'&&!isMine(w)),d=db.cartD.map(W).filter(w=>w&&w.digital&&w.approval==='approved'&&!isMine(w));if(!l.length&&!d.length)return;
const n=val('cn'),p=val('cp'),a=l.length?val('ca'):'';
if(!me())return toast('กรุณาเข้าสู่ระบบก่อนสั่งซื้อ'),to('#/login');
if(!chk('ce',[[n.length<2,'ชื่อผู้รับอย่างน้อย 2 ตัวอักษร'],[!PH.test(p),'เบอร์โทรต้องเป็นตัวเลข 10 หลักขึ้นต้นด้วย 0'],[l.length&&a.length<10,'ที่อยู่สั้นเกินไป (อย่างน้อย 10 ตัวอักษร)']]))return;
const o={id:'OD'+String(Date.now()).slice(-7),items:l.map(w=>w.id),dl:d.map(w=>w.id),name:n,phone:p,addr:a||'(ไฟล์ดิจิทัล — ไม่ต้องจัดส่ง)',total:l.reduce((x,w)=>x+w.price,0)+d.reduce((x,w)=>x+w.digital.price,0)+(l.length?SHIP:0),rate:RATE(),cut:cutOf(l.reduce((x,w)=>x+w.price,0)+d.reduce((x,w)=>x+w.digital.price,0)),status:0,date:new Date().toLocaleString('th-TH'),uid:db.session};
l.forEach(w=>w.status='sold');db.orders.unshift(o);db.cart=[];db.cartD=[];log('สร้าง','คำสั่งซื้อ',o.id,'ยอด '+o.total+(d.length?` (รวมไฟล์ดิจิทัล ${d.length})`:''));save();toast('สร้างคำสั่งซื้อแล้ว');location.hash='#/orders'}
const trackHTML=o=>{const sh=Object.entries(o.ships||{}),tr=new Set(sh.map(([k,s])=>s.tracking));return sh.map(([k,s])=>`<p>ส่งโดย ${esc(A(k)?.name||'ศิลปิน')} · เลขพัสดุ: <b>${esc(s.tracking)}</b></p>`).join('')+(o.tracking&&!String(o.tracking).split(', ').every(x=>tr.has(x))?`<p>เลขพัสดุ: <b>${esc(o.tracking)}</b></p>`:'')};
P.ship=()=>{const ar=me().artist,l=shipList();return`<h2>ออเดอร์ที่ต้องจัดส่ง</h2><p class="mu">แสดงออเดอร์ที่แอดมินยืนยันการชำระเงินแล้ว กรอกเลขพัสดุเพื่อแจ้งจัดส่ง (แอดมินจัดส่งแทนได้เช่นกัน)</p>`+(l.map(o=>{const my=o.ships?.[ar],its=o.items.filter(i=>W(i)?.artist===ar).map(i=>esc(W(i)?.title)).join(', ');return`<div class="box"><div class="row"><b class="grow">${o.id}</b><span class="mu">${esc(o.date)}</span></div><div class="mu">${its}<br>ผู้รับ: ${esc(o.name)} ${esc(o.phone)}<br>${esc(o.addr)}</div>${my?`<p><span class="tag ok">ส่งแล้ว</span> เลขพัสดุ: <b>${esc(my.tracking)}</b>${my.t?` · ${dTH(my.t)}`:''}</p>`:o.status>=2?`<p><span class="tag ok">แอดมินจัดส่งแล้ว</span>${o.tracking?` เลขพัสดุ: <b>${esc(o.tracking)}</b>`:''}</p>`:`<div class="row"><input id="tk${o.id}" placeholder="เลขพัสดุ (ตัวอักษร/ตัวเลข 6–30 ตัว)" class="grow"><button class="btn" onclick="shipA('${o.id}')">ยืนยันจัดส่ง</button></div><div class="err" id="tke${o.id}"></div>`}</div>`}).join('')||'<p class="mu">ยังไม่มีออเดอร์ที่ต้องจัดส่ง</p>')};
function shipA(id){const ar=me()?.artist,o=gO(id);if(!ar||!o)return;const t=val('tk'+id);if(!chk('tke'+id,[[!/^[A-Za-z0-9-]{6,30}$/.test(t),'เลขพัสดุต้องเป็นตัวอักษร/ตัวเลข 6–30 ตัว'],[o.status!==1||o.cancelled,'จัดส่งไม่ได้ในสถานะนี้'],[o.ships?.[ar],'แจ้งจัดส่งไปแล้ว']]))return;o.ships={...(o.ships||{}),[ar]:{tracking:t,t:Date.now()}};if(!REMOTE){const ow=[...new Set(o.items.map(i=>W(i)?.artist))];if(ow.every(k=>o.ships[k])){o.status=2;o.tracking=Object.values(o.ships).map(s=>s.tracking).join(', ')}}log('จัดส่ง','คำสั่งซื้อ',id,t+' (ศิลปิน)');save();toast('แจ้งจัดส่งแล้ว');go()}
function ocard(o,ad){const pay=o.status===0&&!o.cancelled;
return`<div class="box"><div class="row"><b class="grow">${o.id}</b><span class="mu">${o.date}</span>${o.cancelled?'<span class="tag bad">ยกเลิก</span>':''}</div>
<div class="mu">${o.items.map(i=>esc(W(i)?.title)).concat((o.dl||[]).map(i=>esc(W(i)?.title)+' (ไฟล์ดิจิทัล)')).concat(o.com?['งานจ้างวาด: '+esc(gC(o.com)?.title)]:[]).join(', ')} · ${esc(o.name)} ${esc(o.phone)}<br>${esc(o.addr)}</div><p><b>รวม ${baht(o.total)}</b></p>${ad&&o.cut!=null?`<p class="mu">ค่าคอมมิชชัน ${baht(o.cut)} (${o.rate}%) · ศิลปินได้รับ ${baht(o.total-(o.items.length?SHIP:0)-o.cut)}</p>`:''}
<div class="steps">${ST.map((s,i)=>`<div class="${!o.cancelled&&i<=o.status?'on':''}">${s}</div>`).join('')}</div>${trackHTML(o)}
${!ad&&(o.dl||[]).length&&o.status>=1&&!o.cancelled?`<div class="box"><b>ดาวน์โหลดไฟล์ความละเอียดสูง</b>${o.dl.map(i=>`<div class="row" style="margin-top:6px"><span class="grow">${esc(W(i)?.title)} <span class="mu">${W(i)?.digital?.w}×${W(i)?.digital?.h}</span></span><button class="btn sm" onclick="dlFile('${i}')">⬇ ดาวน์โหลด</button></div>`).join('')}</div>`:''}${pay&&!ad?`<div class="row" style="align-items:flex-start"><div class="qrb"><img src="${qrSrc()}" alt="QR รับเงิน" class="qrimg"><div class="amt">ยอดที่ต้องโอน<br><b>${baht(o.total)}</b></div><div class="mu">สแกนแล้วกรอกยอดเอง (QR นี้ไม่ระบุยอดให้อัตโนมัติ) จากนั้นแนบสลิปด้านข้าง</div></div><div class="grow"><label>แนบสลิปโอนเงิน</label><input type="file" accept="image/*" onchange="upSlip('${o.id}',this.files[0])">${o.slip?'<p class="tag ok">ส่งสลิปแล้ว รอแอดมินตรวจ</p>':''}</div></div>`:''}
${o.slip&&ad?`<img class="slip" src="${o.slip}" alt="สลิป">`:''}
${ad&&!o.cancelled?`<div class="row" style="margin-top:8px">${o.status===0?`<button class="btn g" onclick="setSt('${o.id}',1)">ยืนยันรับชำระ</button>`:''}${o.status===1&&o.items.length?`<button class="btn" onclick="ship('${o.id}')">จัดส่งแล้ว</button>`:''}${o.status===1&&!o.items.length&&!o.com?`<button class="btn g" onclick="setSt('${o.id}',3)">สำเร็จ</button>`:''}${o.status===2?`<button class="btn g" onclick="setSt('${o.id}',3)">สำเร็จ</button>`:''}${o.status<2?`<button class="btn r" onclick="cancelO('${o.id}')">ยกเลิก</button>`:''}</div>`:''}</div>`}
P.orders=()=>{if(isMgr())return'<p>แอดมินจัดการคำสั่งซื้อที่หน้า “แอดมิน”</p>';return`<h2>คำสั่งซื้อของฉัน</h2>`+(db.orders.filter(o=>o.uid===db.session).map(o=>ocard(o,false)).join('')||'<p class="mu">ยังไม่มีคำสั่งซื้อ</p>')};
function upSlip(id,f){if(!f)return;resize(f,600,d=>{db.orders.find(o=>o.id===id).slip=d;log('แนบสลิป','คำสั่งซื้อ',id);save();toast('แนบสลิปแล้ว');go()})}
P.login=()=>`<div class="box" style="max-width:380px;margin:auto"><h2>เข้าสู่ระบบ</h2><label>อีเมล</label><input id="le" type="email"><label>รหัสผ่าน</label><input id="lp" type="password" onkeydown="if(event.key==='Enter')doLogin()"><div class="err" id="lerr"></div><br><button class="btn" onclick="doLogin()">เข้าสู่ระบบ</button> <a href="#/register" style="color:var(--ac)">สมัครสมาชิก</a></div>`;
P.register=()=>`<div class="box" style="max-width:420px;margin:auto"><h2>สมัครสมาชิก</h2><label>ชื่อ-นามสกุล</label><input id="rn"><label>อีเมล</label><input id="re" type="email"><label>เบอร์โทร</label><input id="rp" placeholder="0812345678"><label>รหัสผ่าน (อย่างน้อย 6 ตัว)</label><input id="rw" type="password"><label>ยืนยันรหัสผ่าน</label><input id="rc" type="password"><label style="display:flex;gap:8px;align-items:center"><input type="checkbox" id="ra" style="width:auto"> ต้องการสมัครเป็นศิลปิน (กรอกข้อมูลต่อในขั้นถัดไป)</label><div class="err" id="rerr"></div><br><button class="btn" onclick="doReg()">สมัครสมาชิก</button></div>`;
P.profile=()=>{const u=me(),a=u.artist&&A(u.artist);return`<div class="box" style="max-width:480px"><h2>โปรไฟล์ของฉัน</h2><div class="mu">${esc(u.email)} · ${ROLE[u.role]}</div><label>ชื่อ</label><input id="pn" value="${esc(u.name)}"><label>เบอร์โทร</label><input id="pp2" value="${esc(u.phone)}">${a?`<label>คณะ/สถาบัน</label><input id="ps" value="${esc(a.school)}"><label>แนะนำตัว</label><textarea id="pb" rows="3">${esc(a.bio)}</textarea>`:''}<label>รหัสผ่านใหม่ (เว้นว่างถ้าไม่เปลี่ยน)</label><input id="pw" type="password">${REMOTE?'<label>รหัสผ่านเดิม (กรอกเมื่อเปลี่ยนรหัสผ่าน)</label><input id="po" type="password">':''}<div class="err" id="perr"></div><br><button class="btn" onclick="saveProfile()">บันทึก</button></div>`};
P.upload=()=>rentOk()?fw(null):'<div class="box" style="max-width:480px"><h2>ค่าพื้นที่ขายหมดอายุ</h2><p>กรุณาต่ออายุ '+baht(RENT)+' / เดือน ก่อนอัปโหลดผลงานใหม่</p><a class="btn" href="#/apply">ต่ออายุตอนนี้</a></div>';
P.edit=id=>{const w=W(id);return w&&canEdit(w)?fw(w):'<p>ไม่มีสิทธิ์แก้ไขผลงานนี้</p>'};
const gO=id=>db.orders.find(o=>o.id===id),ost=o=>o.cancelled?'ยกเลิก':ST[o.status];
function setSt(id,s){if(!isMgr())return;const o=gO(id),b=o.status;o.status=s;if(o.com&&s===1){const c=gC(o.com);if(c&&!c.end&&c.status===2)c.status=3}log('เปลี่ยนสถานะ','คำสั่งซื้อ',id,ST[b]+' → '+ST[s]);save();go()}
function ship(id){const t=prompt('เลขพัสดุ');if(t===null)return;if(!/^[A-Za-z0-9-]{6,30}$/.test(t.trim()))return toast('เลขพัสดุต้องเป็นตัวอักษร/ตัวเลข 6–30 ตัว');gO(id).tracking=t.trim();setSt(id,2)}
function cancelO(id){if(!isMgr()||!confirm('ยกเลิกคำสั่งซื้อนี้? ผลงานจะกลับมาว่าง'))return;const o=gO(id);o.cancelled=1;if(o.com){const c=gC(o.com);if(c&&c.status<=3)c.end='cancelled'}o.items.forEach(i=>{if(W(i))W(i).status='available'});log('ยกเลิก','คำสั่งซื้อ',id);save();go()}
function appr(id,s){if(!isMgr())return;W(id).approval=s;log(s==='approved'?'อนุมัติ':'ไม่อนุมัติ','ผลงาน',id,W(id).title);save();go()}
function showO(id){$('#od').innerHTML=ocard(gO(id),true);$('#od').scrollIntoView({behavior:'smooth'})}
function chRole(id,r){const u=db.users.find(x=>x.id===id);if(u.role==='admin'&&r!=='admin'&&db.users.filter(x=>x.role==='admin').length<2){toast('ต้องมีแอดมินอย่างน้อย 1 คน');return go()}log('เปลี่ยนบทบาท','ผู้ใช้',id,u.email+': '+ROLE[u.role]+' → '+ROLE[r]);u.role=r;save();go()}
function delUser(id){const u=db.users.find(x=>x.id===id);
if(u.id===db.session)return toast('ลบบัญชีตัวเองไม่ได้');if(u.role==='admin'&&db.users.filter(x=>x.role==='admin').length<2)return toast('ต้องมีแอดมินอย่างน้อย 1 คน');
if(db.orders.some(o=>o.uid===id)||(u.artist&&db.works.some(w=>w.artist===u.artist))||db.coms.some(c=>c.uid===id||(u.artist&&c.artist===u.artist)))return toast('ลบไม่ได้: ผู้ใช้มีคำสั่งซื้อหรือผลงานอยู่');
if(!confirm('ลบผู้ใช้ '+u.email+' ?'))return;db.users=db.users.filter(x=>x.id!==id);db.apps=db.apps.filter(a=>a.uid!==id);db.likes=db.likes.filter(l=>l.u!==id);db.follows=db.follows.filter(f=>f.u!==id);db.reviews=db.reviews.filter(r=>r.u!==id);log('ลบ','ผู้ใช้',id,u.email);save();go()}
async function addUser(){const n=val('an'),e=val('ae').toLowerCase(),w=$('#aw').value,r=val('ar');
if(!chk('aerr',[[n.length<2,'ชื่ออย่างน้อย 2 ตัวอักษร'],[!EM.test(e),'รูปแบบอีเมลไม่ถูกต้อง'],[!REMOTE&&db.users.some(u=>u.email===e),'อีเมลนี้ถูกใช้แล้ว'],[w.length<6,'รหัสผ่านอย่างน้อย 6 ตัวอักษร']]))return;
if(REMOTE){const x=await api('adminUser',{name:n,email:e,password:w,role:r});if(!chk('aerr',[[!x.ok,x.err||'เพิ่มผู้ใช้ไม่สำเร็จ']]))return;log('เพิ่ม','ผู้ใช้',x.user.id,e+' ('+ROLE[r]+')');save();await flush();V=null;await pull(true);go();return}
const u={id:'u'+Date.now(),name:n,email:e,phone:'',pass:H(w),role:r};db.users.push(u);log('เพิ่ม','ผู้ใช้',u.id,e+' ('+ROLE[r]+')');save();go()}
function catErr(n,skip){return chk('cerr',[[n.length<2||n.length>30,'ชื่อหมวด 2–30 ตัวอักษร'],[db.cats.some((c,i)=>c===n&&i!==skip),'มีหมวดนี้แล้ว']])}
function addCat(){const n=val('nc');if(!catErr(n,-1))return;db.cats.push(n);log('เพิ่ม','หมวดหมู่',n);save();go()}
function renCat(i){const n=(prompt('ชื่อหมวดใหม่',db.cats[i])||'').trim();if(!n||n===db.cats[i])return;if(!catErr(n,i))return toast('ชื่อไม่ถูกต้องหรือซ้ำ');const o=db.cats[i];db.works.forEach(w=>{if(w.cat===o)w.cat=n});db.cats[i]=n;log('แก้ไข','หมวดหมู่',o,o+' → '+n);save();go()}
function delCat(i){const c=db.cats[i];if(db.works.some(w=>w.cat===c))return toast('ลบไม่ได้: ยังมีผลงานในหมวดนี้');if(!confirm('ลบหมวด '+c+' ?'))return;db.cats.splice(i,1);log('ลบ','หมวดหมู่',c);save();go()}
function savePP(){const v=val('sp').replace(/\D/g,'');if(!chk('serr',[[![10,13].includes(v.length),'ต้องเป็นตัวเลข 10 หรือ 13 หลัก']]))return;log('แก้ไข','ตั้งค่า','PromptPay',db.pp+' → '+v);db.pp=v;save();toast('บันทึกแล้ว')}
const bars=p=>{const m=Math.max(1,...p.map(x=>x[1]));return p.map(([k,v,l])=>`<div class="row" style="margin:4px 0"><div style="width:120px">${esc(k)}</div><div class="grow"><div class="bb" style="width:${v/m*100}%"></div></div><b>${l??v}</b></div>`).join('')||'<p class="mu">ยังไม่มีข้อมูล</p>'};
const AD={};
AD.dash=()=>{const ok=db.orders.filter(o=>!o.cancelled&&o.status>=1),byC={},byA={};
ok.forEach(o=>[...o.items.map(i=>[i,0]),...(o.dl||[]).map(i=>[i,1])].forEach(([i,dg])=>{const w=W(i);if(!w)return;const pr=dg?(w.digital?.price||0):w.price;byC[w.cat]=(byC[w.cat]||0)+pr;const n=A(w.artist)?.name||'-';byA[n]=(byA[n]||0)+pr}));
const top=o=>Object.entries(o).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([k,v])=>[k,v,baht(v)]);
const kp=[['รายได้ (ชำระแล้ว)',baht(ok.reduce((s,o)=>s+o.total,0))],['ค่าคอมมิชชัน (ชำระแล้ว)',baht(ok.reduce((s,o)=>s+(o.cut||0),0))],['รายได้ค่าพื้นที่ขาย',baht(db.apps.filter(x=>x.status==='approved'&&x.fee).reduce((s,x)=>s+x.fee,0))],['คำสั่งซื้อทั้งหมด',db.orders.length],['รอชำระ',db.orders.filter(o=>!o.cancelled&&o.status===0).length],['ผลงานรออนุมัติ',db.works.filter(w=>w.approval==='pending').length],['ผลงานที่ขายแล้ว',db.works.filter(w=>w.status==='sold').length],['รีวิวทั้งหมด',db.reviews.length],['งานจ้างวาดที่กำลังดำเนินการ',db.coms.filter(c=>!c.end&&c.status<5).length],['ไฟล์ดิจิทัลที่ขายได้',ok.reduce((a,o)=>a+(o.dl||[]).length,0)],['สมาชิก',db.users.length],['ใบสมัครศิลปินรอตรวจ',db.apps.filter(a=>a.status==='pending').length]];
return`<div class="kpis">${kp.map(([l,v])=>`<div class="box"><div class="mu">${l}</div><h2>${v}</h2></div>`).join('')}</div><div class="two"><div class="box"><h3>คำสั่งซื้อตามสถานะ</h3>${bars([...ST,'ยกเลิก'].map(s=>[s,db.orders.filter(o=>ost(o)===s).length]))}</div><div class="box"><h3>รายได้ตามหมวด</h3>${bars(top(byC))}</div></div><div class="box"><h3>ศิลปินยอดขายสูงสุด</h3>${bars(top(byA))}</div>`};
AD.works=()=>dt('works',db.works,[{h:'ผลงาน',t:w=>w.title,f:w=>`<a href="#/work/${w.id}" style="color:var(--ac)">${esc(w.title)}</a>`},{h:'ศิลปิน',t:w=>A(w.artist)?.name||'-'},{h:'หมวด',t:w=>w.cat},{h:'ราคา',t:w=>w.price,f:w=>baht(w.price)},{h:'อนุมัติ',t:w=>AP[w.approval]},{h:'การขาย',t:w=>w.status==='sold'?'ขายแล้ว':'ว่าง'},
{h:'จัดการ',t:()=>'',f:w=>`<div class="row">${w.approval==='pending'?`<button class="btn g sm" onclick="appr('${w.id}','approved')">อนุมัติ</button><button class="btn r sm" onclick="appr('${w.id}','rejected')">ไม่ผ่าน</button>`:''}<a class="btn o sm" href="#/edit/${w.id}">แก้ไข</a><button class="btn r sm" onclick="delWork('${w.id}')">ลบ</button></div>`}],{fk:w=>AP[w.approval],fo:Object.values(AP)});
AD.orders=()=>dt('orders',db.orders,[{h:'เลขที่',t:o=>o.id},{h:'วันที่',t:o=>o.date},{h:'ผู้รับ',t:o=>o.name},{h:'ยอด',t:o=>o.total,f:o=>baht(o.total)},{h:'ค่าคอมฯ',t:o=>o.cut||0,f:o=>o.cut!=null?baht(o.cut):'-'},{h:'สถานะ',t:ost},{h:'สลิป',t:o=>o.slip?'มี':'-'},{h:'',t:()=>'',f:o=>`<button class="btn o sm" onclick="showO('${o.id}')">รายละเอียด</button>`}],{fk:ost,fo:[...ST,'ยกเลิก']})+'<div id="od"></div>';
AD.users=()=>`<div class="box" style="max-width:520px"><h3>เพิ่มผู้ใช้</h3><div class="row"><input id="an" placeholder="ชื่อ" style="flex:1"><input id="ae" placeholder="อีเมล" style="flex:1"></div><div class="row" style="margin:6px 0"><input id="aw" type="password" placeholder="รหัสผ่าน (≥6)" style="flex:1"><select id="ar" style="flex:1">${Object.keys(ROLE).map(r=>`<option value="${r}">${ROLE[r]}</option>`).join('')}</select></div><div class="err" id="aerr"></div><button class="btn" onclick="addUser()">เพิ่ม</button></div>`+dt('users',db.users,[{h:'ชื่อ',t:u=>u.name},{h:'อีเมล',t:u=>u.email},{h:'บทบาท',t:u=>ROLE[u.role],f:u=>`<select style="width:auto" onchange="chRole('${u.id}',this.value)">${Object.keys(ROLE).map(r=>`<option value="${r}" ${u.role===r?'selected':''}>${ROLE[r]}</option>`).join('')}</select>`},{h:'ศิลปิน',t:u=>u.artist?'ใช่':'-'},{h:'',t:()=>'',f:u=>`<button class="btn r sm" onclick="delUser('${u.id}')">ลบ</button>`}],{fk:u=>ROLE[u.role],fo:Object.values(ROLE)});
AD.cats=()=>`<div class="box" style="max-width:520px"><h3>หมวดหมู่ผลงาน</h3>${db.cats.map((c,i)=>`<div class="row" style="margin:6px 0"><span class="grow">${esc(c)} <span class="mu">(${db.works.filter(w=>w.cat===c).length} ชิ้น)</span></span><button class="btn o sm" onclick="renCat(${i})">เปลี่ยนชื่อ</button><button class="btn r sm" onclick="delCat(${i})">ลบ</button></div>`).join('')}<div class="row" style="margin-top:10px"><input id="nc" placeholder="ชื่อหมวดใหม่" style="flex:1"><button class="btn" onclick="addCat()">เพิ่ม</button></div><div class="err" id="cerr"></div></div>`;
AD.logs=()=>dt('logs',db.logs,[{h:'เวลา',t:l=>l.t},{h:'ผู้ทำ',t:l=>l.u},{h:'บทบาท',t:l=>ROLE[l.r]||l.r},{h:'การกระทำ',t:l=>l.act},{h:'ข้อมูล',t:l=>l.ent},{h:'รหัส',t:l=>l.id},{h:'รายละเอียด',t:l=>l.d}],{fk:l=>l.act,fo:[...new Set(db.logs.map(l=>l.act))]});
AD.set=()=>`${COMMBOX()}${WMBOX()}${QRBOX()}${REMOTE?`<div class="box"><b>ข้อมูลตัวอย่าง</b><p class="mu">นำเข้าศิลปินและผลงานตัวอย่าง 18 ชิ้นเข้าสู่ระบบ (ไม่รวมบัญชีผู้ใช้)</p><button class="btn" onclick="importSeed()">นำเข้าผลงานตัวอย่าง</button></div>`:`<div class="box"><button class="btn r" onclick="if(confirm('ล้างข้อมูลทั้งหมดและเริ่มใหม่?')){localStorage.removeItem(K);location.reload()}">รีเซ็ตข้อมูลทดลอง</button></div>`}`;
const COMMBOX=()=>`<div class="box" style="max-width:420px"><label>อัตราค่าคอมมิชชัน (% ของราคาผลงาน ไม่รวมค่าส่ง)</label><input id="cmr" type="number" min="0" max="50" step="1" value="${RATE()}"><div class="mu">มีผลกับคำสั่งซื้อใหม่เท่านั้น คำสั่งซื้อเดิมใช้อัตราที่บันทึกไว้ตอนสั่ง</div><div class="err" id="cmerr"></div><br><button class="btn" onclick="saveComm()">บันทึกอัตราค่าคอมมิชชัน</button></div>`;
function saveComm(){const t=val('cmr'),n=+t;if(!chk('cmerr',[[t===''||!Number.isInteger(n)||n<0||n>50,'อัตราต้องเป็นจำนวนเต็ม 0–50']]))return;log('แก้ไข','ตั้งค่า','ค่าคอมมิชชัน',RATE()+'% → '+n+'%');db.comm=n;save();toast('บันทึกแล้ว');go()}
const myApp=()=>db.apps.filter(a=>a.uid===db.session).pop();
const rentBox=()=>`<div class="box" style="margin:10px 0"><b>ค่าพื้นที่ขายผลงาน ${baht(RENT)} / เดือน (${RDAYS} วัน)</b><div class="row" style="align-items:flex-start;margin-top:8px"><div class="qrb"><img src="${qrSrc()}" alt="QR รับเงิน" class="qrimg"><div class="amt">ยอดที่ต้องโอน<br><b>${baht(RENT)}</b></div><div class="mu">สแกนด้วย QR เดียวกับการชำระค่าผลงาน (ไม่ระบุยอดอัตโนมัติ) แล้วแนบสลิปด้านข้าง</div></div><div class="grow"><label>แนบสลิปโอนเงิน (รูปภาพ)</label><input type="file" id="rsl" accept="image/*"></div></div></div>`;
P.apply=()=>{const u=me(),a=myApp();
if(u.artist){const un=A(u.artist)?.until,ok=rentOk();
if(a?.status==='pending')return`<div class="box" style="max-width:480px"><h2>ส่งสลิปต่ออายุแล้ว</h2><p>ส่งเมื่อ ${esc(a.date)} — รอแอดมิน/เจ้าหน้าที่ตรวจสลิป</p></div>`;
return`<div class="box" style="max-width:480px"><h2>ค่าพื้นที่ขายผลงาน</h2><p>${un?`สิทธิ์ขายของคุณ${ok?'ใช้ได้ถึง':'หมดอายุเมื่อ'} <b>${dTH(un)}</b>`:'สิทธิ์ขายของคุณยังไม่มีวันหมดอายุ'}</p>${a?.status==='rejected'&&a.kind==='renew'?`<p class="err">สลิปครั้งก่อนไม่ผ่าน: ${esc(a.note)}</p>`:''}${rentBox()}<div class="err" id="aperr"></div><button class="btn" onclick="submitApp('renew')">ส่งสลิปต่ออายุ</button> <a class="btn o" href="#/upload">＋ อัปโหลดผลงาน</a></div>`}
if(u.role!=='customer')return'<div class="box"><p>เฉพาะบัญชีลูกค้าเท่านั้นที่สมัครเป็นศิลปินได้</p></div>';
if(a?.status==='pending')return`<div class="box" style="max-width:480px"><h2>ส่งใบสมัครแล้ว</h2><p>ส่งเมื่อ ${esc(a.date)} พร้อมสลิปค่าพื้นที่ขาย — รอแอดมิน/เจ้าหน้าที่ตรวจสอบ เมื่อผ่านแล้วเมนู “อัปโหลดผลงาน” จะปรากฏ</p></div>`;
return`<div class="box" style="max-width:480px"><h2>สมัครเป็นศิลปิน</h2>${a?.status==='rejected'?`<p class="err">ใบสมัครครั้งก่อนไม่ผ่าน: ${esc(a.note)} — แก้ไขแล้วสมัครใหม่ได้</p>`:''}<p class="mu">ศิลปินเสียค่าพื้นที่ขายผลงาน ${baht(RENT)} ต่อเดือน ทีมงานจะตรวจสลิปและใบสมัครก่อนเปิดสิทธิ์ขาย และผลงานทุกชิ้นยังต้องผ่านการอนุมัติก่อนเผยแพร่</p><label>ชื่อที่ใช้แสดง</label><input id="ans" value="${esc(u.name)}"><label>คณะ/สถาบัน</label><input id="asc"><label>แนะนำตัว/ประสบการณ์ (10–300 ตัวอักษร)</label><textarea id="abi" rows="4"></textarea><label style="display:flex;gap:8px;align-items:center"><input type="checkbox" id="aag" style="width:auto"> ยืนยันว่าเป็นเจ้าของผลงานที่จะนำมาขาย</label>${rentBox()}<div class="err" id="aperr"></div><br><button class="btn" onclick="submitApp('new')">ส่งใบสมัครพร้อมสลิป</button></div>`};
async function submitApp(kind){const u=me(),f=$('#rsl')?.files[0];
if(myApp()?.status==='pending'||(kind==='new')===!!u.artist)return;
let n,sc,b;if(kind==='new'){n=val('ans');sc=val('asc');b=val('abi')}else{const ar=A(u.artist);n=ar.name;sc=ar.school||'-';b=ar.bio||'-'}
if(!chk('aperr',[...(kind==='new'?[[n.length<2,'ชื่ออย่างน้อย 2 ตัวอักษร'],[sc.length<2,'กรอกคณะ/สถาบัน'],[b.length<10||b.length>300,'แนะนำตัว 10–300 ตัวอักษร'],[!$('#aag').checked,'ต้องยืนยันความเป็นเจ้าของผลงาน']]:[]),[!f,'กรุณาแนบสลิปค่าพื้นที่ขาย '+RENT+' บาท'],[f&&!/^image\//.test(f.type),'สลิปต้องเป็นไฟล์รูปภาพ'],[f&&f.size>10e6,'ไฟล์สลิปต้องไม่เกิน 10 MB']]))return;
const slip=await rz(f,600);
const a={id:'ap'+Date.now(),uid:db.session,kind,name:n,school:sc,bio:b,fee:RENT,slip,status:'pending',date:new Date().toLocaleString('th-TH')};
db.apps.push(a);log(kind==='new'?'ส่งใบสมัคร':'ส่งสลิปต่ออายุ','ศิลปิน',a.id,n);save();toast('ส่งแล้ว รอตรวจสลิป');go()}
function viewSlip(id){const a=db.apps.find(x=>x.id===id);if(!a?.slip)return;$('#sv').innerHTML=`<div class="box"><b>สลิปค่าพื้นที่ขาย — ${esc(a.name)} (${baht(a.fee||RENT)})</b><br><img class="slip" src="${a.slip}" alt="สลิป"></div>`;$('#sv').scrollIntoView({behavior:'smooth'})}
function approveApp(id){if(!isMgr())return;const a=db.apps.find(x=>x.id===id),u=a&&db.users.find(x=>x.id===a.uid);if(!u||a.status!=='pending')return;
if(a.kind==='renew'){const ar=A(u.artist);if(!ar)return;ar.until=Math.max(Date.now(),ar.until||0)+RDAYS*864e5;a.status='approved';log('อนุมัติ','ต่ออายุพื้นที่ขาย',id,u.email+' ถึง '+dTH(ar.until));save();return go()}
if(u.artist)return;
const ar={id:'a'+Date.now(),name:a.name,school:a.school,bio:a.bio,until:Date.now()+RDAYS*864e5};db.artists.push(ar);u.artist=ar.id;a.status='approved';log('อนุมัติ','ใบสมัครศิลปิน',id,u.email);save();go()}
function rejectApp(id){if(!isMgr())return;const a=db.apps.find(x=>x.id===id);if(a.status!=='pending')return;const n=(prompt('เหตุผลที่ไม่ผ่าน (อย่างน้อย 3 ตัวอักษร)')||'').trim();if(n.length<3)return toast('กรุณาระบุเหตุผล');a.status='rejected';a.note=n;log('ไม่อนุมัติ','ใบสมัครศิลปิน',id,n);save();go()}
AD.apps=()=>dt('apps',db.apps,[{h:'ผู้สมัคร',t:a=>a.name},{h:'อีเมล',t:a=>db.users.find(u=>u.id===a.uid)?.email||'-'},{h:'คณะ/สถาบัน',t:a=>a.school},{h:'แนะนำตัว',t:a=>a.bio,f:a=>esc(a.bio.length>60?a.bio.slice(0,60)+'…':a.bio)},{h:'วันที่',t:a=>a.date},{h:'ประเภท',t:a=>a.kind==='renew'?'ต่ออายุ':'สมัครใหม่'},{h:'สลิป',t:a=>a.slip?'มี':'-',f:a=>a.slip?`<button class="btn o sm" onclick="viewSlip('${a.id}')">ดูสลิป</button>`:'-'},{h:'สถานะ',t:a=>AP[a.status]},{h:'จัดการ',t:()=>'',f:a=>a.status==='pending'?`<div class="row"><button class="btn g sm" onclick="approveApp('${a.id}')">อนุมัติ</button><button class="btn r sm" onclick="rejectApp('${a.id}')">ไม่ผ่าน</button></div>`:esc(a.note||'')}],{fk:a=>AP[a.status],fo:Object.values(AP)})+'<div id="sv"></div>';
P.work=id=>{const h=P.work0(id),w=W(id);if(!w)return h;const ap=db.works.filter(x=>x.approval==='approved'),k=ap.findIndex(x=>x.id===id),wn=k>=0&&ap.length>1?`<div class="wnav"><button class="btn o sm" onclick="stepWork(-1)">‹ รูปก่อนหน้า</button><span class="mu">${k+1} / ${ap.length}</span><button class="btn o sm" onclick="stepWork(1)">รูปถัดไป ›</button></div>`:'';const o=db.works.filter(x=>x.artist===w.artist&&x.id!==id&&x.approval==='approved').slice(0,4);
const dg=w.digital&&w.approval==='approved'?`<div class="box"><div class="row"><div class="grow"><h3>ไฟล์ดิจิทัลความละเอียดสูง</h3><div class="mu">${w.digital.w}×${w.digital.h} พิกเซล · ${w.digital.fmt}${w.digital.size?' · '+(w.digital.size/1048576).toFixed(1)+' MB':''} · ไม่มีลายน้ำ · ดาวน์โหลดได้หลังแอดมินยืนยันการชำระเงิน · ใช้ส่วนตัว ไม่อนุญาตให้จำหน่ายต่อ</div></div><b style="font-size:20px">${baht(w.digital.price)}</b><button class="btn" ${db.cartD.includes(id)||isMine(w)?'disabled':''} onclick="addDigital('${id}')">${isMine(w)?'ผลงานของคุณ':db.cartD.includes(id)?'อยู่ในตะกร้าแล้ว':'ซื้อไฟล์ดิจิทัล'}</button></div></div>`:'';const lb=`<div class="row" style="margin-bottom:8px"><button class="btn ${liked(id)?'':'o'} sm" onclick="wish('${id}')">♥ ${liked(id)?'ถูกใจแล้ว':'ถูกใจ'} (${lc(id)})</button>${rcW(id)?`<span>${stars(avgW(id))} <b>${avgW(id).toFixed(1)}</b> (${rcW(id)} รีวิว)</span>`:'<span class="mu">ยังไม่มีรีวิว</span>'}${tagChips(w)}</div>`;return wn+lb+h+dg+rvSec(id)+(o.length?`<h3 style="margin-top:24px">ผลงานอื่นของ ${esc(A(w.artist)?.name)}</h3><div class="grid">${o.map(x=>wc(x)).join('')}</div>`:'')+recSec(w)};
const sec=t=>`<div class="sec"><h2>${t}</h2></div>`;
const wc=w=>{const ok=w.status==='available'&&w.approval==='approved',inC=db.cart.includes(w.id);
return`<div class="pc"><a href="#/work/${w.id}" class="pt">${art(w)}${ok?'':stTag(w)}</a><button class="hb ${liked(w.id)?'on':''}" onclick="wish('${w.id}')" aria-label="ถูกใจ">♥</button><a href="#/work/${w.id}" class="pn">${esc(w.title)}</a><div class="mu">${esc(A(w.artist)?.name)}</div><div class="mu">♥ ${lc(w.id)}${rcW(w.id)?` · <span class="st">★</span> ${avgW(w.id).toFixed(1)} (${rcW(w.id)})`:''}</div><div class="pr">${baht(w.price)}</div>${isMine(w)?`<a class="btn o cta" href="#/edit/${w.id}">แก้ไขผลงาน</a>`:`<button class="btn o cta" ${ok&&!inC?'':'disabled'} onclick="addCart('${w.id}')">${inC?'อยู่ในตะกร้า':ok?'ใส่ตะกร้า':'ไม่พร้อมขาย'}</button>`}</div>`};
function hsearch(){const v=val('hs'),a=db.artists.find(x=>x.name===v);F.q=a?'':v;F.artist=a?a.id:'';F.cat='';F.min='';F.max='';F.page=0;to('#/');setTimeout(()=>$('#shop')?.scrollIntoView({behavior:'smooth'}),80)}
function stepWork(d){const id=location.hash.split('/')[2],l=db.works.filter(x=>x.approval==='approved'),k=l.findIndex(x=>x.id===id);if(k<0||l.length<2)return;DIR=d>0?'n':'p';location.hash='#/work/'+l[(k+d+l.length)%l.length].id}
function shop(k,v){F.cat='';F.artist='';F[k]=v;F.page=0;to('#/');setTimeout(()=>$('#shop')?.scrollIntoView({behavior:'smooth'}),80)}
let HI=0,NAVF=0,DIR='';
function heroHTML(){const ok=db.works.filter(w=>w.approval==='approved'),pool=ok.filter(w=>!w.img),l=(pool.length>1?pool:ok).sort((a,b)=>b.price-a.price).slice(0,4);if(l.length<2)return'';
post.push(()=>{slide(0);clearInterval(window.HT);const h=setInterval(()=>slide(HI+1),5000);h.unref?.();window.HT=h});
return`<div id="hero"><div id="trk">${l.map(w=>`<a class="sl" href="#/work/${w.id}">${art(w,1)}<div class="cap"><b>${esc(w.title)}</b><span>${esc(A(w.artist)?.name)} · ${baht(w.price)}</span></div></a>`).join('')}</div></div><div class="dots">${l.map((_,i)=>`<span onclick="slide(${i})"></span>`).join('')}</div>`}
function slide(n){const t=$('#trk');if(!t||!t.style)return;const k=t.children.length,w=$('#hero').clientWidth;HI=(n+k)%k;t.style.transform=`translateX(${w*.12-HI*w*.78}px)`;[...t.children].forEach((c,i)=>c.classList.toggle('on',i===HI));document.querySelectorAll('.dots span').forEach((d,i)=>d.classList.toggle('on',i===HI))}
P.wishlist=()=>{const l=db.likes.filter(x=>x.u===db.session).map(x=>W(x.w)).filter(w=>w&&w.approval==='approved');return sec('รายการที่ถูกใจ ♥')+(l.length?`<div class="grid">${l.map(wc).join('')}</div>`:'<p class="mu" style="text-align:center">ยังไม่มีรายการที่ถูกใจ — กดหัวใจที่ผลงานเพื่อเก็บไว้ดูภายหลัง</p>')};
const qrSrc=()=>db.qr||QR0;
const QRBOX=()=>`<div class="box" style="max-width:420px"><label>QR รับเงิน (PromptPay) ที่แสดงตอนลูกค้าชำระเงิน</label><img src="${qrSrc()}" alt="QR" class="qrimg" style="max-width:220px"><label>เปลี่ยนเป็น QR ใหม่ (รูปภาพ ไม่เกิน 5 MB)</label><input id="qf" type="file" accept="image/*"><div class="err" id="qerr"></div><br><button class="btn" onclick="saveQR()">อัปโหลด QR ใหม่</button> <button class="btn o" onclick="resetQR()">ใช้ QR ตั้งต้น</button></div>`;
async function saveQR(){const f=$('#qf').files[0];if(!chk('qerr',[[!f,'กรุณาเลือกไฟล์รูป QR'],[f&&!/^image\//.test(f.type),'ต้องเป็นไฟล์รูปภาพ'],[f&&f.size>5e6,'ไฟล์ต้องไม่เกิน 5 MB']]))return;db.qr=await rz(f,600);log('แก้ไข','ตั้งค่า','QR รับเงิน','เปลี่ยนรูป QR');save();toast('บันทึกแล้ว');go()}
function resetQR(){if(!db.qr)return;db.qr='';log('แก้ไข','ตั้งค่า','QR รับเงิน','กลับเป็นค่าตั้งต้น');save();go()}
// ===== จ้างศิลปินวาดรูป (commission) =====
const CS=['รอศิลปินตอบรับ','เสนอราคาแล้ว','รอชำระเงิน','กำลังวาด','ส่งมอบแล้ว','สำเร็จ'],SIZES=['A4 (21×29.7 ซม.)','A3 (29.7×42 ซม.)','A2 (42×59.4 ซม.)','ตามที่ตกลงกับศิลปิน'],STYLES=['สีน้ำ','สีน้ำมัน','อะคริลิก','ดิจิทัลอาร์ต','ลายเส้น','ภาพเหมือนบุคคล','อื่นๆ (ระบุในรายละเอียด)'];
const gC=id=>db.coms.find(x=>x.id===id),cst=c=>c.end==='declined'?'ศิลปินปฏิเสธ':c.end==='cancelled'?'ยกเลิก':CS[c.status],minD=()=>new Date(Date.now()+7*864e5).toISOString().slice(0,10);
P.hire=aid=>{const u=me(),l=db.artists.filter(a=>a.id!==u.artist);return sec('จ้างศิลปินวาดรูป')+`<div class="box" style="max-width:560px;margin:auto"><p class="mu">ส่งรายละเอียดงานให้ศิลปิน ศิลปินจะตอบรับพร้อมเสนอราคาและระยะเวลา คุณยืนยันราคาแล้วจึงชำระเงิน ผู้ซื้อได้รับงานเป็นไฟล์ดิจิทัล</p><label>เลือกศิลปิน</label><select id="hA">${l.map(a=>`<option value="${a.id}" ${a.id===aid?'selected':''}>${esc(a.name)} — ${esc(a.school)}</option>`).join('')}</select><label>หัวข้องาน</label><input id="hT"><label>รายละเอียดที่ต้องการ (20–1,000 ตัวอักษร)</label><textarea id="hB" rows="5"></textarea>
<div class="row"><div class="grow"><label>ขนาดงาน</label><select id="hS">${SIZES.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="grow"><label>สไตล์/เทคนิค</label><select id="hY">${STYLES.map(x=>`<option>${x}</option>`).join('')}</select></div></div>
<div class="row"><div class="grow"><label>งบประมาณ (บาท)</label><input id="hG" type="number"></div><div class="grow"><label>ต้องการรับงานภายในวันที่</label><input id="hD" type="date" min="${minD()}"></div></div><label>รูปอ้างอิง (ไม่บังคับ ไม่เกิน 5 MB)</label><input id="hF" type="file" accept="image/*"><div class="err" id="herr"></div><br><button class="btn" onclick="sendHire()">ส่งคำขอจ้าง</button></div>`};
async function sendHire(){const u=me(),a=val('hA'),t=val('hT'),b=val('hB'),g=+val('hG'),d=val('hD'),f=$('#hF').files[0];
if(!chk('herr',[[!A(a)||a===u.artist,'กรุณาเลือกศิลปิน (จ้างตัวเองไม่ได้)'],[t.length<3||t.length>80,'หัวข้อ 3–80 ตัวอักษร'],[b.length<20||b.length>1000,'รายละเอียด 20–1,000 ตัวอักษร'],[!Number.isInteger(g)||g<300||g>200000,'งบประมาณเป็นจำนวนเต็ม 300–200,000 บาท'],[!d||d<minD(),'วันที่ต้องการรับงานต้องห่างจากวันนี้อย่างน้อย 7 วัน'],[f&&!/^image\//.test(f.type),'รูปอ้างอิงต้องเป็นไฟล์รูปภาพ'],[f&&f.size>5e6,'รูปอ้างอิงต้องไม่เกิน 5 MB']]))return;
const ref=f?await rz(f,700):'',c={id:'C'+String(Date.now()).slice(-7),uid:db.session,artist:a,title:t,brief:b,size:val('hS'),style:val('hY'),budget:g,deadline:d,ref,status:0,rev:0,date:new Date().toLocaleString('th-TH')};
db.coms.unshift(c);log('ส่งคำขอ','งานจ้างวาด',c.id,`${t} → ${A(a).name}`);save();toast('ส่งคำขอแล้ว');to('#/jobs')}
function ACT(c,r){if(c.end)return'';const i=c.id,dl=`<button class="btn g sm" onclick="dlCom('${i}')">⬇ ดาวน์โหลดไฟล์งาน</button>`;
if(c.status===5)return dl;
if(r==='a'){if(c.status===0)return`<div class="row"><input id="qp-${i}" type="number" placeholder="ราคา (บาท)" style="flex:1"><input id="qd-${i}" type="number" placeholder="ใช้เวลากี่วัน" style="flex:1"><input id="qn-${i}" placeholder="หมายเหตุ (ไม่บังคับ)" style="flex:2"></div><div class="err" id="qe-${i}"></div><button class="btn g sm" onclick="quoteCom('${i}')">เสนอราคา</button> <button class="btn r sm" onclick="declineCom('${i}')">ปฏิเสธงาน</button>`;
 if(c.status===3)return`<div class="row"><input id="df-${i}" type="file" accept="image/jpeg,image/png,image/webp" style="flex:2"><input id="dn-${i}" placeholder="ข้อความถึงผู้จ้าง" style="flex:2"></div><div class="err" id="de-${i}"></div><button class="btn sm" onclick="deliverCom('${i}')">ส่งมอบงาน</button>`}
if(r==='c'){if(c.status===0)return`<button class="btn r sm" onclick="cancelCom('${i}')">ยกเลิกคำขอ</button>`;
 if(c.status===1)return`<button class="btn g sm" onclick="acceptCom('${i}')">ยืนยันราคาและไปชำระเงิน</button> <button class="btn r sm" onclick="cancelCom('${i}')">ปฏิเสธข้อเสนอ</button>`;
 if(c.status===2)return`<a class="btn sm" href="#/orders">ไปชำระเงิน</a> <button class="btn r sm" onclick="cancelCom('${i}')">ยกเลิก</button>`;
 if(c.status===4)return`<button class="btn g sm" onclick="confirmCom('${i}')">ยืนยันรับงาน</button> <button class="btn o sm" onclick="reviseCom('${i}')">ขอแก้ไข (${2-(c.rev||0)} ครั้งที่เหลือ)</button>`}
return''}
function ccard(c,r){const a=A(c.artist),cu=db.users.find(x=>x.id===c.uid);
return`<div class="box"><div class="row"><b class="grow">${esc(c.title)}</b><span class="tag ${c.end?'bad':c.status===5?'ok':'w'}">${cst(c)}</span></div><div class="mu">${c.id} · ${c.date} · ${r==='a'?'ผู้จ้าง: '+esc(cu?.name):'ศิลปิน: '+esc(a?.name)} · ${esc(c.size)} · ${esc(c.style)} · งบ ${baht(c.budget)} · ต้องการภายใน ${esc(c.deadline)}</div><p>${esc(c.brief)}</p>${c.ref?`<img class="slip" src="${c.ref}" alt="รูปอ้างอิง">`:''}
${c.quote?`<p><b>ราคาที่เสนอ ${baht(c.quote.price)}</b> · ใช้เวลา ${c.quote.days} วัน${c.quote.note?' · '+esc(c.quote.note):''}</p>`:''}${c.reason?`<p class="err">เหตุผล: ${esc(c.reason)}</p>`:''}${c.revNote&&c.status===3?`<p class="mu">คำขอแก้ไขล่าสุด: ${esc(c.revNote)}</p>`:''}
<div class="steps">${CS.map((x,i)=>`<div class="${!c.end&&i<=c.status?'on':''}">${x}</div>`).join('')}</div>${c.delivery?`<div><b>งานที่ส่งมอบ</b>${c.status<5?' <span class="mu">(ตัวอย่างมีลายน้ำ ไฟล์จริงดาวน์โหลดได้หลังยืนยันรับงาน)</span>':''}<br><img class="slip" style="max-width:260px" src="${c.delivery.img}" alt="งานที่ส่งมอบ"><p class="mu">${esc(c.delivery.note)}</p></div>`:''}${ACT(c,r)}${r==='c'&&c.status===5?rvForm('c',c.id):''}</div>`}
P.jobs=()=>{const u=me(),mine=db.coms.filter(c=>c.uid===u.id),inc=u.artist?db.coms.filter(c=>c.artist===u.artist):[];
return sec('งานจ้างวาด')+`<div class="row" style="justify-content:center;margin-bottom:16px"><a class="btn" href="#/hire">＋ จ้างศิลปินวาดรูป</a></div>`+(u.artist?`<h3>งานที่ได้รับจ้าง (${inc.length})</h3>${inc.map(c=>ccard(c,'a')).join('')||'<p class="mu">ยังไม่มีคำขอจ้าง</p>'}`:'')+`<h3>งานที่ฉันจ้าง (${mine.length})</h3>${mine.map(c=>ccard(c,'c')).join('')||'<p class="mu">ยังไม่เคยจ้างงาน</p>'}`};
function quoteCom(id){const c=gC(id);if(!c||c.status!==0||c.end||c.artist!==me()?.artist)return;const p=+val('qp-'+id),d=+val('qd-'+id),n=val('qn-'+id);
if(!chk('qe-'+id,[[!Number.isInteger(p)||p<300||p>200000,'ราคาเป็นจำนวนเต็ม 300–200,000 บาท'],[!Number.isInteger(d)||d<1||d>90,'จำนวนวัน 1–90'],[n.length>200,'หมายเหตุไม่เกิน 200 ตัวอักษร']]))return;
c.quote={price:p,days:d,note:n};c.status=1;log('เสนอราคา','งานจ้างวาด',id,baht(p)+' / '+d+' วัน');save();go()}
function declineCom(id){const c=gC(id);if(!c||c.status!==0||c.end||c.artist!==me()?.artist)return;const n=(prompt('เหตุผลที่ปฏิเสธงาน (อย่างน้อย 3 ตัวอักษร)')||'').trim();if(n.length<3)return toast('กรุณาระบุเหตุผล');c.end='declined';c.reason=n;log('ปฏิเสธงาน','งานจ้างวาด',id,n);save();go()}
function acceptCom(id){const c=gC(id);if(!c||c.status!==1||c.end||c.uid!==db.session)return;const u=me(),o={id:'OD'+String(Date.now()).slice(-7),items:[],dl:[],com:id,name:u.name,phone:u.phone||'-',addr:'(งานจ้างวาด — ส่งมอบเป็นไฟล์ดิจิทัล)',total:c.quote.price,rate:RATE(),cut:cutOf(c.quote.price),status:0,date:new Date().toLocaleString('th-TH'),uid:db.session};
db.orders.unshift(o);c.orderId=o.id;c.status=2;log('ยืนยันราคา','งานจ้างวาด',id,'สร้างคำสั่งซื้อ '+o.id);save();toast('สร้างคำสั่งซื้อแล้ว กรุณาชำระเงิน');location.hash='#/orders'}
function cancelCom(id){const c=gC(id);if(!c||c.end||c.uid!==db.session||c.status>2)return;if(!confirm('ยกเลิกงานจ้างนี้?'))return;c.end='cancelled';const o=c.orderId&&gO(c.orderId);if(o&&o.status===0)o.cancelled=1;log('ยกเลิก','งานจ้างวาด',id);save();go()}
async function deliverCom(id){const c=gC(id);if(!c||c.status!==3||c.end||c.artist!==me()?.artist)return;const f=$('#df-'+id).files[0],n=val('dn-'+id);
if(!chk('de-'+id,[[!f,'กรุณาเลือกไฟล์งานที่ส่งมอบ'],[f&&!['image/jpeg','image/png','image/webp'].includes(f.type),'ไฟล์ต้องเป็น JPG, PNG หรือ WebP'],[f&&f.size>40e6,'ไฟล์ต้องไม่เกิน 40 MB'],[n.length>300,'ข้อความไม่เกิน 300 ตัวอักษร']]))return;
try{await hiPut('c:'+id,f)}catch(e){return toast('บันทึกไฟล์ไม่สำเร็จ')}
const img=await rz(f,800,db.wm.text+' • '+A(c.artist).name);c.delivery={img,note:n,date:new Date().toLocaleString('th-TH'),ext:f.type.split('/')[1].replace('jpeg','jpg')};c.status=4;log('ส่งมอบงาน','งานจ้างวาด',id,c.title);save();go()}
function confirmCom(id){const c=gC(id);if(!c||c.status!==4||c.end||c.uid!==db.session)return;c.status=5;const o=c.orderId&&gO(c.orderId);if(o)o.status=3;log('ยืนยันรับงาน','งานจ้างวาด',id);save();toast('ยืนยันรับงานแล้ว ดาวน์โหลดไฟล์ได้เลย');go()}
function reviseCom(id){const c=gC(id);if(!c||c.status!==4||c.end||c.uid!==db.session)return;if((c.rev||0)>=2)return toast('ขอแก้ไขได้ไม่เกิน 2 ครั้ง');const n=(prompt('ต้องการให้แก้ไขอะไร (อย่างน้อย 5 ตัวอักษร)')||'').trim();if(n.length<5)return toast('กรุณาระบุรายละเอียดการแก้ไข');c.rev=(c.rev||0)+1;c.revNote=n;c.status=3;log('ขอแก้ไข','งานจ้างวาด',id,n);save();go()}
async function dlCom(id){const c=gC(id);if(!c||c.status!==5||!(c.uid===db.session||isMgr()||c.artist===me()?.artist))return;try{const b=await hiGet('c:'+id);if(!b)return toast('ไม่พบไฟล์ในเบราว์เซอร์นี้ (เดโม: ไฟล์เก็บไว้ในเครื่องของศิลปิน)');const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${c.title}.${c.delivery.ext}`;document.body.appendChild(a);a.click();a.remove();toast('เริ่มดาวน์โหลดแล้ว')}catch(e){toast('ดาวน์โหลดไม่สำเร็จ')}}
AD.jobs=()=>dt('jobs',db.coms,[{h:'รหัส',t:c=>c.id},{h:'หัวข้อ',t:c=>c.title},{h:'ผู้จ้าง',t:c=>db.users.find(u=>u.id===c.uid)?.name||'-'},{h:'ศิลปิน',t:c=>A(c.artist)?.name||'-'},{h:'งบ',t:c=>c.budget,f:c=>baht(c.budget)},{h:'ราคาเสนอ',t:c=>c.quote?.price||0,f:c=>c.quote?baht(c.quote.price):'-'},{h:'สถานะ',t:cst},{h:'คำสั่งซื้อ',t:c=>c.orderId||'-'}],{fk:cst,fo:[...CS,'ศิลปินปฏิเสธ','ยกเลิก']});
// ===== ถูกใจ / รีวิว / ติดตามศิลปิน =====
function initSocial(){if(!db.likes){db.likes=[];db.works.forEach((w,i)=>['u3','u4','u5','u6'].forEach((u,j)=>{if((i+j)%3===0&&db.users.some(x=>x.id===u))db.likes.push({u,w:w.id})}))}
if(!db.follows)db.follows=[['u6','a1'],['u3','a2'],['u4','a1'],['u5','a1'],['u6','a3']].map(([u,a])=>({u,a}));
if(!db.reviews)db.reviews=[['u4','w1',5,'สีสวยมาก แสงตอนพระอาทิตย์ตกดูมีมิติ ได้รับงานเรียบร้อย ห่อมาดีมาก'],['u6','w1',4,'ภาพสวยตรงตามรูป สีสดกว่าในจอเล็กน้อย โดยรวมพอใจครับ'],['u3','w2',5,'ภาพพิมพ์ลายไม้ละเอียดมาก เห็นรอยหมึกชัดเจน ชอบมากค่ะ'],['u6','w3',4,'ไฟล์ดิจิทัลคมชัด นำไปพิมพ์เป็นโปสเตอร์ได้สบาย'],['u5','w4',5,'ภาพป่าหมอกให้ความรู้สึกสงบ แขวนในห้องนอนแล้วดูดีมาก']].filter(([u,r])=>db.users.some(x=>x.id===u)&&db.works.some(w=>w.id===r)).map(([u,ref,rating,text],i)=>({id:'Rs'+i,u,kind:'w',ref,artist:db.works.find(w=>w.id===ref).artist,rating,text,date:'12/9/2569'}))}
const liked=id=>db.likes.some(l=>l.u===db.session&&l.w===id),lc=id=>db.likes.filter(l=>l.w===id).length;
function wish(id){if(!me()){toast('กรุณาเข้าสู่ระบบเพื่อกดถูกใจ');return to('#/login')}const i=db.likes.findIndex(l=>l.u===db.session&&l.w===id);i<0?db.likes.push({u:db.session,w:id}):db.likes.splice(i,1);save();go()}
const isFollow=a=>db.follows.some(f=>f.u===db.session&&f.a===a);
function follow(a){if(!me())return to('#/login');if(me().artist===a)return;const i=db.follows.findIndex(f=>f.u===db.session&&f.a===a);i<0?db.follows.push({u:db.session,a}):db.follows.splice(i,1);save();go()}
const avgOf=l=>l.length?l.reduce((a,r)=>a+r.rating,0)/l.length:0,stars=v=>{const n=Math.round(v);return`<span class="st">${'★'.repeat(n)}${'☆'.repeat(5-n)}</span>`},rW=id=>db.reviews.filter(r=>r.kind==='w'&&r.ref===id),avgW=id=>avgOf(rW(id)),rcW=id=>rW(id).length;
const rvOK=(k,ref)=>{const u=me();if(!u)return false;if(k==='w'){const w=W(ref);return !!w&&w.artist!==u.artist&&db.orders.some(o=>o.uid===u.id&&!o.cancelled&&o.status>=1&&(o.items.includes(ref)||(o.dl||[]).includes(ref)))}const c=gC(ref);return !!c&&c.uid===u.id&&c.status===5&&!c.end};
const rvForm=(k,ref)=>{const ex=db.reviews.find(x=>x.u===db.session&&x.kind===k&&x.ref===ref),key=k+ref;
return`<div class="box" style="margin-top:10px"><b>${ex?'แก้ไขรีวิวของคุณ':k==='c'?'รีวิวศิลปิน':'เขียนรีวิว'}</b><div style="margin-top:6px"><select id="rs-${key}" style="width:auto">${[5,4,3,2,1].map(n=>`<option value="${n}" ${ex?.rating===n?'selected':''}>${'★'.repeat(n)}${'☆'.repeat(5-n)} (${n})</option>`).join('')}</select></div><textarea id="rt-${key}" rows="3" placeholder="เล่าประสบการณ์ของคุณ (10–500 ตัวอักษร)" style="margin-top:6px">${esc(ex?.text)}</textarea><div class="err" id="re-${key}"></div><button class="btn sm" onclick="saveRv('${k}','${ref}')">${ex?'บันทึกการแก้ไข':'ส่งรีวิว'}</button>${ex?` <button class="btn r sm" onclick="delRv('${ex.id}')">ลบรีวิว</button>`:''}</div>`};
const rvItem=(r,showWork)=>`<div class="box"><div class="row"><b>${esc(db.users.find(u=>u.id===r.u)?.name||'ผู้ใช้')}</b>${stars(r.rating)}<span class="tag ok">${r.kind==='c'?'ผู้จ้างงาน':'ซื้อแล้ว'}</span><span class="grow"></span><span class="mu">${esc(r.date)}</span>${r.u===db.session||isMgr()?`<button class="btn r sm" onclick="delRv('${r.id}')">ลบ</button>`:''}</div>${showWork&&r.kind==='w'?`<div class="mu">ผลงาน: <a href="#/work/${r.ref}" style="color:var(--ac)">${esc(W(r.ref)?.title)}</a></div>`:''}<p style="margin:.4em 0 0">${esc(r.text)}</p></div>`;
const rvSec=id=>{const l=rW(id);return sec('รีวิวจากผู้ซื้อ')+`<div style="max-width:720px;margin:auto">${l.length?`<p>${stars(avgW(id))} <b>${avgW(id).toFixed(1)}</b> จาก ${l.length} รีวิว</p>`:''}${l.map(r=>rvItem(r)).join('')||'<p class="mu">ยังไม่มีรีวิว</p>'}${rvOK('w',id)?rvForm('w',id):me()?'<p class="mu">รีวิวได้เฉพาะผู้ที่ซื้อผลงานนี้และชำระเงินแล้ว</p>':'<p class="mu"><a href="#/login" style="color:var(--ac)">เข้าสู่ระบบ</a> เพื่อรีวิวหลังซื้อผลงาน</p>'}</div>`};
function saveRv(k,ref){const key=k+ref,r=+val('rs-'+key),t=val('rt-'+key);if(!rvOK(k,ref))return toast('รีวิวได้เฉพาะผู้ซื้อที่ชำระเงินแล้ว');
if(!chk('re-'+key,[[!Number.isInteger(r)||r<1||r>5,'เลือกคะแนน 1–5 ดาว'],[t.length<10||t.length>500,'ข้อความรีวิว 10–500 ตัวอักษร']]))return;
const ex=db.reviews.find(x=>x.u===db.session&&x.kind===k&&x.ref===ref),d=new Date().toLocaleDateString('th-TH');
if(ex){const o=ex.rating;ex.rating=r;ex.text=t;ex.date=d;log('แก้ไข','รีวิว',ex.id,`${o}→${r} ดาว`)}
else{const n={id:'R'+Date.now(),u:db.session,kind:k,ref,artist:k==='w'?W(ref).artist:gC(ref).artist,rating:r,text:t,date:d};db.reviews.unshift(n);log('เพิ่ม','รีวิว',n.id,`${r} ดาว (${k==='w'?W(ref).title:gC(ref).title})`)}
save();toast('บันทึกรีวิวแล้ว');go()}
function delRv(id){const x=db.reviews.find(r=>r.id===id);if(!x||!(x.u===db.session||isMgr()))return;if(!confirm('ลบรีวิวนี้?'))return;db.reviews=db.reviews.filter(r=>r.id!==id);log('ลบ','รีวิว',id,`${x.rating} ดาว โดย ${db.users.find(u=>u.id===x.u)?.email||'-'}`);save();go()}
P.artist=id=>{const h=P.artist0(id),a=A(id);if(!a)return h;const rs=db.reviews.filter(r=>r.artist===id),n=db.follows.filter(f=>f.u&&f.a===id).length,u=me(),fo=isFollow(id);
return`<div class="row" style="margin-bottom:10px">${rs.length?`<span>${stars(avgOf(rs))} <b>${avgOf(rs).toFixed(1)}</b> (${rs.length} รีวิว)</span>`:'<span class="mu">ยังไม่มีรีวิว</span>'}<span class="mu">· ผู้ติดตาม ${n} คน</span><span class="grow"></span>${u&&u.artist===id?'':`<button class="btn ${fo?'o':''}" onclick="follow('${id}')">${fo?'✓ กำลังติดตาม':'＋ ติดตาม'}</button>`}</div>`+h+(rs.length?sec('รีวิวศิลปิน')+`<div style="max-width:720px;margin:auto">${rs.slice(0,10).map(r=>rvItem(r,1)).join('')}</div>`:'')};
P.following=()=>{const ids=db.follows.filter(f=>f.u===db.session).map(f=>f.a),l=db.works.filter(w=>ids.includes(w.artist)&&w.approval==='approved').reverse();
return sec('ศิลปินที่ติดตาม')+(ids.length?`<div class="row" style="margin-bottom:16px">${ids.map(a=>`<a class="btn o sm" href="#/artist/${a}">${esc(A(a)?.name)}</a>`).join('')}</div><h3>ผลงานล่าสุดจากศิลปินที่คุณติดตาม</h3><div class="grid">${l.map(wc).join('')||'<p class="mu">ยังไม่มีผลงาน</p>'}</div>`:'<p class="mu" style="text-align:center">ยังไม่ได้ติดตามศิลปิน — เข้าไปที่หน้าศิลปินแล้วกด “＋ ติดตาม”</p>')};
AD.reviews=()=>dt('reviews',db.reviews,[{h:'ผู้รีวิว',t:r=>db.users.find(u=>u.id===r.u)?.name||'-'},{h:'ประเภท',t:r=>r.kind==='c'?'ศิลปิน (งานจ้าง)':'ผลงาน'},{h:'เรื่อง',t:r=>r.kind==='w'?(W(r.ref)?.title||'-'):(gC(r.ref)?.title||'-')},{h:'คะแนน',t:r=>r.rating,f:r=>stars(r.rating)},{h:'ข้อความ',t:r=>r.text,f:r=>esc(r.text.length>70?r.text.slice(0,70)+'…':r.text)},{h:'วันที่',t:r=>r.date},{h:'',t:()=>'',f:r=>`<button class="btn r sm" onclick="delRv('${r.id}')">ลบ</button>`}],{fk:r=>r.rating+' ดาว',fo:['5 ดาว','4 ดาว','3 ดาว','2 ดาว','1 ดาว']});
// ===== แนะนำผลงานที่คล้ายกัน (แท็ก + โทนสีของภาพ) =====
function histOf(cv){const t=document.createElement('canvas');t.width=t.height=32;const x=t.getContext('2d');x.drawImage(cv,0,0,32,32);const d=x.getImageData(0,0,32,32).data,a=Array(HB).fill(0);for(let i=0;i<d.length;i+=4)a[hsvBin(d[i],d[i+1],d[i+2])]++;return normH(a)}
const colSim=(a,b)=>a&&b?a.reduce((t,x,i)=>t+Math.min(x,b[i]),0):0;
function sim(a,b){const A0=new Set(a.tags||[]),B0=b.tags||[],hit=B0.filter(t=>A0.has(t)),u=new Set([...A0,...B0]).size||1,cs=colSim(a.sig,b.sig);return{s:.5*(hit.length/u)+.35*cs+.15*(a.cat===b.cat?1:0),tags:hit,cs}}
function similar(w,n=4){const p=db.works.filter(x=>x.id!==w.id&&x.approval==='approved'&&x.status==='available').map(x=>({w:x,...sim(w,x)})).sort((a,b)=>b.s-a.s),same=p.filter(x=>x.w.cat===w.cat).slice(0,n);return same.length>=n?same:[...same,...p.filter(x=>x.w.cat!==w.cat).slice(0,n-same.length)]}
const recCard=p=>`<div>${wc(p.w)}<div class="mu why">${p.from?`คล้ายกับ “${esc(p.from)}”`:`คล้าย ${Math.round(p.s*100)}%`}${p.tags.length?' · แท็กตรงกัน: '+p.tags.slice(0,3).map(esc).join(', '):''}${p.cs>.5?' · โทนสีใกล้เคียง':''}</div></div>`;
const tagChips=w=>(w.tags||[]).map(t=>`<a class="tag" href="#/" data-v="${esc(t)}" onclick="F.cat='';F.artist='';F.min='';F.max='';F.q=this.dataset.v;F.page=0;to('#/');return false">#${esc(t)}</a>`).join(' ');
const recSec=w=>{const l=similar(w,4);return l.length?sec('ผลงานที่คล้ายกัน')+`<p class="mu" style="text-align:center;margin-top:-10px">เลือกจากแท็กและโทนสีของ “${esc(w.title)}” โดยให้ความสำคัญกับหมวด ${esc(w.cat)}ก่อน</p><div class="grid">${l.map(recCard).join('')}</div>`:''};
const recHome=()=>{const u=me();if(!u)return'';const bought=[...new Set(db.orders.filter(o=>o.uid===u.id&&!o.cancelled).flatMap(o=>[...o.items,...(o.dl||[])]))].map(W).filter(Boolean);if(!bought.length)return'';
const own=new Set(bought.map(w=>w.id)),sc={};bought.forEach(b=>db.works.forEach(x=>{if(own.has(x.id)||x.approval!=='approved'||x.status!=='available'||(u.artist&&x.artist===u.artist))return;const r=sim(b,x);if(!sc[x.id]||r.s>sc[x.id].s)sc[x.id]={w:x,s:r.s,tags:r.tags,cs:r.cs,from:b.title}}));
const l=Object.values(sc).sort((a,b)=>b.s-a.s).slice(0,4);return l.length?sec('แนะนำสำหรับคุณ')+`<p class="mu" style="text-align:center;margin-top:-10px">เลือกจากแท็กและโทนสีของผลงานที่คุณซื้อ</p><div class="grid">${l.map(recCard).join('')}</div>`:''};
// ===== โหมดออนไลน์: ซิงก์ข้อมูลกับเซิร์ฟเวอร์ (Vercel Function + Upstash Redis) =====
const LK='artcorner_local',KEYS={works:x=>x.id,artists:x=>x.id,users:x=>x.id,orders:x=>x.id,coms:x=>x.id,reviews:x=>x.id,apps:x=>x.id,likes:x=>x.u+'|'+x.w,follows:x=>x.u+'|'+x.a,logs:x=>x.i};
async function api(a,b={}){try{const r=await fetch('/api/app',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({a,token:TOK,...b}),signal:(typeof AbortSignal!=='undefined'&&AbortSignal.timeout)?AbortSignal.timeout(a==='ping'?6000:20000):undefined});const j=await r.json().catch(()=>null);return j||{ok:false,err:'เซิร์ฟเวอร์ไม่ตอบกลับ',net:1}}catch(e){return{ok:false,err:'เชื่อมต่อเซิร์ฟเวอร์ไม่ได้',net:1}}}
const persistLocal=()=>{try{localStorage.setItem(LK,JSON.stringify({tok:TOK,session:db.session,cart:db.cart,cartD:db.cartD}))}catch(e){}};
const mapOf=(c,arr)=>{const m={};(arr||[]).forEach(x=>{const k=KEYS[c](x);if(k)m[k]=JSON.stringify(x)});return m};
function snapshot(){BASE={};Object.keys(KEYS).forEach(c=>{BASE[c]=mapOf(c,db[c])});BASE.settings={cats:JSON.stringify(db.cats),wm:JSON.stringify(db.wm),qr:JSON.stringify(db.qr||''),comm:JSON.stringify(db.comm??10)}}
function collect(){const ops=[];Object.keys(KEYS).forEach(c=>{const cur=mapOf(c,db[c]),b=BASE[c]||{};for(const k in cur)if(b[k]!==cur[k])ops.push({c,id:k,v:JSON.parse(cur[k])});if(c!=='logs')for(const k in b)if(!(k in cur))ops.push({c,id:k,v:null})});
const st={cats:db.cats,wm:db.wm,qr:db.qr||'',comm:db.comm??10};for(const k in st)if(BASE.settings[k]!==JSON.stringify(st[k]))ops.push({c:'settings',id:k,v:st[k]});return ops}
async function push(){const ops=collect();if(!ops.length)return;const r=await api('sync',{ops});
if(r.ok){ops.forEach(o=>{if(o.c==='settings')BASE.settings[o.id]=JSON.stringify(o.v);else if(o.v===null)delete BASE[o.c][o.id];else BASE[o.c][o.id]=JSON.stringify(o.v)});V=null}
else if(r.net)toast(r.err);else{toast(r.err||'บันทึกไม่สำเร็จ');V=null;await pull(true,true)}}
const FORMS=/^(hire|upload|edit|apply|profile|login|register)$/;
function rerender(){const a=document.activeElement,p=location.hash.slice(2).split('/')[0];if(a&&/INPUT|TEXTAREA|SELECT/.test(a.tagName))return;FORMS.test(p)?nav():go()}
async function pull(force,discard){const r=await api('state',{since:force?null:V});if(!r.ok||r.same)return;if(!discard&&collect().length)return;
V=r.v;if(!r.auth&&TOK){TOK='';db.session=null;persistLocal()}
const sig=JSON.stringify(r.data)+(r.me?r.me.id:'');if(sig===LAST&&!discard)return;LAST=sig;
Object.keys(KEYS).forEach(c=>{db[c]=r.data[c]||[]});db.cats=r.data.settings.cats;db.wm=r.data.settings.wm;db.qr=r.data.settings.qr||'';db.comm=r.data.settings.comm??10;if(r.me)db.session=r.me.id;snapshot();rerender()}
const flush=async()=>{let q;do{q=Q;await q}while(q!==Q)};
function poll(){if(REMOTE&&document.visibilityState!=='hidden')Q=Q.then(async()=>{await push();await pull()}).catch(()=>{})}
async function boot(){const r=await api('ping');REMOTE=!!(r.ok&&r.remote);if(!REMOTE){go();return}
let L={};try{L=JSON.parse(localStorage.getItem(LK)||'{}')}catch(e){}
TOK=L.tok||'';db={session:L.session||null,cart:L.cart||[],cartD:L.cartD||[],wish:[],cats:[...CATS],wm:{text:'ArtCorner',op:.35},qr:''};Object.keys(KEYS).forEach(c=>{db[c]=[]});snapshot();
await pull(true,true);go();setInterval(poll,15000);if(document.addEventListener)document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')poll()})}
function importSeed(){if(!confirm('นำเข้าศิลปินและผลงานตัวอย่าง 18 ชิ้น? (ไม่รวมบัญชีผู้ใช้)'))return;const s=seed();s.artists.forEach(a=>{if(!db.artists.some(x=>x.id===a.id))db.artists.push(a)});s.works.forEach(w=>{if(!db.works.some(x=>x.id===w.id))db.works.push(w)});log('นำเข้า','ข้อมูลตัวอย่าง','-','ผลงาน 18 ชิ้น');save();toast('นำเข้าแล้ว');go()}
const isMine=w=>!!(me()&&me().artist&&w.artist===me().artist);
P.admin=t=>{const tabs=[['dash','📊 Dashboard'],['works','ผลงาน'],['orders','คำสั่งซื้อ'],['apps','ใบสมัครศิลปิน'],['jobs','งานจ้างวาด'],['reviews','รีวิว'],...(isAd()?[['users','ผู้ใช้'],['cats','หมวดหมู่'],['logs','Log'],['set','ตั้งค่า']]:[])];t=tabs.some(x=>x[0]===t)?t:'dash';
return`<div class="row" style="margin-bottom:12px">${tabs.map(([k,l])=>`<a class="btn ${k===t?'':'o'} sm" href="#/admin/${k}">${l}</a>`).join('')}</div>`+AD[t]()};
function go(){if(REMOTE===null){const a=$('#app');if(a)a.innerHTML='<p class="mu" style="text-align:center;margin-top:80px">กำลังโหลด…</p>';return}const h=location.hash.slice(2).split('/'),p=P[h[0]]?h[0]:'home',need={orders:me(),profile:me(),edit:me(),upload:isA(),ship:isA(),admin:isMgr(),apply:me(),hire:me(),jobs:me(),wishlist:me(),following:me()};post=[];clearInterval(window.HT);nav();
$('#app').innerHTML=(p in need&&!need[p])?'<div class="box"><p>ต้องเข้าสู่ระบบด้วยบัญชีที่มีสิทธิ์เพื่อเข้าหน้านี้</p><a class="btn" href="#/login">เข้าสู่ระบบ</a></div>':P[p](h[1]);
const an=NAVF||DIR,ap=$('#app');if(p==='home')drawGrid(an);post.forEach(f=>f());if(an&&ap.classList){ap.classList.remove('pg-in','dir-n','dir-p');void ap.offsetWidth;ap.classList.add(DIR==='n'?'dir-n':DIR==='p'?'dir-p':'pg-in')}NAVF=0;DIR=''}
addEventListener('keydown',e=>{if(!location.hash.startsWith('#/work/')||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='ArrowRight')stepWork(1);if(e.key==='ArrowLeft')stepWork(-1)});addEventListener('scroll',()=>$('#up')?.classList?.toggle('show',scrollY>400));addEventListener('hashchange',()=>{NAVF=1;go();scrollTo(0,0)});go();if(REMOTE===null)BOOT=boot();
